### ISSUE TITLE
Wrong font in the shell everywhere

### ISSUE THREAD

**Issue by vovean** [daniruiz/flat-remix-gnome#101]
![Screenshot from 2019-07-24 15-27-26](https://user-images.githubusercontent.com/19476942/61793334-95b2ee80-ae27-11e9-9c79-b6f287ae3dbe.png)
![My font settings](https://user-images.githubusercontent.com/19476942/61793414-c430c980-ae27-11e9-9602-b6797a55f15d.png)
![image](https://user-images.githubusercontent.com/19476942/61793790-7bc5db80-ae28-11e9-9a2a-dd5cd75e0593.png)

I'm having some issues with incorrect font being used almost everywhere in the shell. You can see that I'm using default Ubuntu font everywhere (picture 2). Still, all the app names, all the info in the top bar, folder labels on the desktop and search results (picture 1) are written in the different from selected font. Actually, I don't even know wht this font is.

It is definitely the Flat Remix bug because when in Tweak Tool I switch the shell theme back to default the font changes to the right one (picture 3).

I'm using Ubuntu 19.04 with GNOME Shell 3.32.0. The Flat Remix theme was installed using apt-get and daniruiz PPA. According to ```ls -la``` executed in my ```.themes``` (not sure if this folder is the right one when installing via apt) folder last update was downloaded April 13. I'm using Flat-Remix-Dark mode

**Comment by akiirui** [comment]
Default fonts of flat-remix
```
font-family: Cantarell, Sans-Serif;
```
If you not have `Cantarell`, fallback to `sans-serif`

check `fc-match sans-serif` and set fontconfig prefer `sans-serif` to `ubuntu`
