### ISSUE TITLE
Oversized Canonical Livepatch Icon

### ISSUE THREAD

**Issue by dav-is** [daniruiz/flat-remix-gnome#103]
The icon for Canonical Livepatch (Ubuntu) is too big and super ugly

![Screenshot from 2019-07-29 11-07-20](https://user-images.githubusercontent.com/11590024/62059337-0cb60180-b1f1-11e9-909b-6a60fa96b81c.png)

It's possible this issue belongs here instead: https://github.com/daniruiz/flat-remix-gtk

**Comment by fdinardo** [comment]
Hi, for what I know this maybe related to two reasons:

1. 

The icon them you are using is not including that icon and the systems loads the default one

**Comment by dav-is** [comment]
My screen is `2560x1440` with `200%`

**Comment by daniruiz** [comment]
The new theme is completely based on the upstream code, so this issue should be fixed
