### ISSUE TITLE
Add color variants that match your GTK3 themes

### ISSUE THREAD

**Issue by craigcbrunner** [daniruiz/flat-remix-gnome#106]
I love your theme, would it be possible add shell color variants that match your GTK themes, I like to use blue-darkest for the shell and its a little annoying that the calendar in the panel uses different colors(green highlight instead of blue).

**Comment by isfalcantara** [comment]
And a solid variant would be nice too, as the transparent top bar caused by the shell theme is very jarring when using a solid GTK theme variant.

**Comment by rustysec** [comment]
I have the opposite problem, setting the green gtk theme but the gnome theme only has blue highlights.

**Comment by daniruiz** [comment]
It's finally done!! :wink:
