### ISSUE TITLE
Network selection dialog using Dark themes have wrong background in PopOS 19.04 

### ISSUE THREAD

**Issue by philong6297** [daniruiz/flat-remix-gnome#107]
This is my settings:
![image](https://user-images.githubusercontent.com/29605147/64218359-7b226980-ceeb-11e9-98e9-f9dcfff28b09.png)
This is network selection dialog using any flat dark themes:
![image](https://user-images.githubusercontent.com/29605147/64218397-a016dc80-ceeb-11e9-957b-0f6d7193c19f.png)

**Comment by daniruiz** [comment]
UUUUuggggg!!!! POP OS does some weird things with their themes and forces some styles with the '!important' rule. :-1: 
I like their themes but I don't know why they have programmed the gnome-shell theme that way :disappointed_relieved: 
I'll try to fix it anyway

**Comment by karabijavad** [comment]
this is happening for me too.
started happening as soon as i upgraded from ubuntu 19.10 to 20.04

**Comment by karabijavad** [comment]
@daniruiz i made a PR to fix the background color for Flat-Remix-Darkest-fullPanel
https://github.com/daniruiz/flat-remix-gnome/pull/132

can you let me know if that is the right file to edit? it seems to work correctly for me. i ran make, make install, then i unloaded and reloaded the theme, and it works.

**Comment by daniruiz** [comment]
Pop OS uses a different theme base for gnome-shell so you need to force the shell to only use flat-remix theme. For that you need to login selecting the Flat-Remix session
![image](https://user-images.githubusercontent.com/12565871/79075776-1935a800-7cf5-11ea-83d4-2c34304fa9c0.png)
