### ISSUE TITLE
Login Screen only works upon restart on Ubuntu 18.04

### ISSUE THREAD

**Issue by LeptoSpira** [daniruiz/flat-remix-gnome#108]
The Login Screen works great when you restart your computer, but does not work once you lock your computer.

**Comment by gjvpaet** [comment]
@LeptoSpira refer to issue #78 and try @andrewc910's solution. It worked for me!

**Comment by LeptoSpira** [comment]
Can confirm `sudo update-alternatives --config gdm3.css` does **not** work,
am trying @andrewc910's solution...

**Comment by LeptoSpira** [comment]
Alright that works! 

I hope @daniruiz impliments an out-of-the-box solution

**Comment by daniruiz** [comment]
Are you using fedora?

**Comment by LeptoSpira** [comment]
> Login Screen only works upon restart on Ubuntu 18.04

**Comment by daniruiz** [comment]
Sorry for the delay but I've been really busy :sweat_smile: 
I've modified the way the theme is installed via the deb package and hopefully, it works better now.
Could you try installing the new package it from the ppa? Also, ensure that you select Flat-Remix inside the login session dialog
![image](https://user-images.githubusercontent.com/12565871/69007215-514de000-093b-11ea-9d43-05ca60f322d5.png)

**Comment by LeptoSpira** [comment]
This works well! Thank you!

**Comment by LeptoSpira** [comment]
Thanks
