### ISSUE TITLE
 Popup menus in Gnome Shell aligned incorrectly

### ISSUE THREAD

**Issue by Sarki** [daniruiz/flat-remix-gnome#109]
Please refer to https://github.com/arc-design/arc-theme/issues/108
The issue is eactly the same, ~~my understanding is that the resolution might be also the same.~~

**Comment by daniruiz** [comment]
I tried to fix it even with the 'hack' mentioned in the issue you provided, but none of the solutions can work without removing the popup outline, which I quite like, so for now it is going to stay like this :disappointed_relieved:

**Comment by Sarki** [comment]
That's fair enough, that was my conclusion as well hence the  text with a strike through line, perhaps someone will come up with another solution.
BTW your work is awesome, thanks for having spent some time on this issue.
