### ISSUE TITLE
Blyr Bug: Botom Border in Panel

### ISSUE THREAD

**Issue by btd1337** [daniruiz/flat-remix-gnome#114]
Gnome 3.34
Theme: Dark and Dark Full

![Captura de tela de 2019-10-13 19-56-22](https://user-images.githubusercontent.com/11943860/66723802-d0f40680-edf3-11e9-9b0c-8329fedb4e1d.png)

![Captura de tela de 2019-10-13 19-55-59](https://user-images.githubusercontent.com/11943860/66723806-d6e9e780-edf3-11e9-8674-bfe2e3223288.png)

![Captura de tela de 2019-10-13 19-54-35](https://user-images.githubusercontent.com/11943860/66723811-ecf7a800-edf3-11e9-9cc5-22aefa4c6ae8.png)

**Comment by daniruiz** [comment]
Fixed on GNOME 3.36
