### ISSUE TITLE
Dark arrow [Dark Full Panel]

### ISSUE THREAD

**Issue by Alexander88207** [daniruiz/flat-remix-gnome#115]
Is that normal? Somehow it looks terrible.
![Screenshot from 2019-10-26 22-43-51](https://user-images.githubusercontent.com/37543796/67625758-6c4c9900-f842-11e9-9dd5-87863b5b1414.png)

**Comment by daniruiz** [comment]
Noup, that isn't normal. This is how it should look like:
![imagen](https://user-images.githubusercontent.com/12565871/67638607-b9824680-f8e6-11e9-8ef6-90457b832dab.png)

Which version of gnome are you using?

**Comment by Alexander88207** [comment]
3.28

**Comment by daniruiz** [comment]
I can't support that many versions, right now the latest GNOME  version is 3.36, 3.28 is 5 versions older. Sorry :(
