### ISSUE TITLE
Unable to install Login Theme

### ISSUE THREAD

**Issue by nayaksoumya56** [daniruiz/flat-remix-gnome#116]
Hi, I am currently running ubuntu 18.04 LTS and installed the theme and icons. i have installed  libglib2.0-dev-bin and imagemagick packages. I cloned the repo as instructed but when i run the make command i keep getting below error:

cp: cannot stat '/tmp/flat-remix-gnome/Flat-Remix-Dark/gnome-shell-theme.gresource': No such file or directory
![flat-remix-make-error](https://user-images.githubusercontent.com/40364491/68274181-6ea6c280-008e-11ea-8442-bc7272bc88c6.png)

**Comment by leocencetti** [comment]
Same here!

**Comment by nayaksoumya56** [comment]
I restarted the machine a couple of times and got the screen. though now it shows up only during sign-in and if i leave the machine locked for too long. if i lock and comeback in a couple of minutes i get native gnome login. is there a fix for this ?

**Comment by taschenlampe** [comment]
I was about to comment on this bug, that there is a missing icon (pointer...svg) in the in all listed assets, but I am happy to see that this bug is fixed with version [20191109]. See if this works for you guys now.

**Comment by daniruiz** [comment]
Sorry guys, I haven't been using gnome-shell this week and didn't have time to check this issue. Today I'll try to fix :wink:

**Comment by daniruiz** [comment]
I've just tested it on Ubuntu 19.10 and it is working again. Can anyone confirm if it is fixed now

**Comment by nayaksoumya56** [comment]
Yep its fixed! thanks a lot! appreciate the work.
