### ISSUE TITLE
dpkg: error 127 

### ISSUE THREAD

**Issue by almerray** [daniruiz/flat-remix-gnome#118]
bro how about this.. some user had same trouble too

dpkg: error processing package flat-remix-gnome (--configure):
installed flat-remix-gnome package post-installation script subprocess returned error exit status 127

thanks for your great creation

**Comment by daniruiz** [comment]
Humm... weird, do you have the following packages installed? `gnome-shell, make, libglib2.0-dev-bin, imagemagick`
If so try completely removing the theme and installing it again.

**Comment by almerray** [comment]
Hi, thanks for your attention and replying my question !
this problem already solved, i reinstall it again

**Comment by daniruiz** [comment]
I did some modifications in the way the theme is installed and it may cause some issues if you have a previous version. I'm glad it helped 😉
