### ISSUE TITLE
COPR package broken

### ISSUE THREAD

**Issue by ChiDal** [daniruiz/flat-remix-gnome#119]
Since the last update, there is no flat remix option in shell theme.
Using fedora rawhide.
![flat-remix-bug](https://user-images.githubusercontent.com/36493671/69751718-9a760f00-1147-11ea-8991-1c327d9845d9.png)
![1111](https://user-images.githubusercontent.com/36493671/69751720-9c3fd280-1147-11ea-92a7-d73f293c4d05.png)

**Comment by daniruiz** [comment]
Could you try removing and reinstalling it? Since the las update now themes aren't directly installed. Now it works by copying the source to /usr/share/flat-remix-gnome and then running `make && make install` so that it can generate a custom login image

**Comment by ChiDal** [comment]
Yeah it works now
