### ISSUE TITLE
Manjaro lockscreen broken

### ISSUE THREAD

**Issue by SrSands** [daniruiz/flat-remix-gnome#120]
I installed the theme from the AUR package applied it but when i couldn't set a background image in the lock screen i decided to roll back and use the default theme.
This is were the problems begins, i cant find the way to apply the default theme to it. I used the tweaks tool but i does not change the lockscreen.
Any help?

**Comment by SrSands** [comment]
Just solved with a default theme reinstall, but it would be nice to get a "cleaner implementation" (not saying that your code is bad) to get the default lockscreen after moving to the default theme for example.

**Comment by daniruiz** [comment]
Unfortunately, GNOME gives no way to install login screen themes, so you need to replace some files which can break things :cry:  I'm sorry this didn't work for you as intended, if this happens again just reinstalling gnome-shell will fix it `sudo pacman -S gnome-shell`

**Comment by SrSands** [comment]
A reinstall of the default theme while it was selected with the tweaks fixed the issue :dancer: . 

 > Unfortunately, GNOME gives no way to install login screen themes, so you need to replace some files which can break things

I didnt know that about gnome so next time i will now what to do.
Muchas gracias de todas fomas !
