### ISSUE TITLE
Wallpapers?

### ISSUE THREAD

**Issue by farshed** [daniruiz/flat-remix-gnome#121]
Hey, can you please upload or provide a link to the wallpapers in the demo? I can't find them anywhere. Thanks. https://drasite.com/img/flat-remix-gnome-full.jpg

**Comment by daniruiz** [comment]
Unfortunately right now I don't have the names of the wallpapers, but all of them where taken from wallhaven.cc
There you'll find lots of awesome wallpapers for your Desktop.
Hope this helps you :wink:
