### ISSUE TITLE
gnome-control-center lost after trying to instal flat-remix

### ISSUE THREAD

**Issue by davajuhda** [daniruiz/flat-remix-gnome#123]
why i cant open my system setting , i think i failed installing the package, i have tried sudo apt-get install gnome-control-center 
output

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-control-center : Depends: language-selector-gnome (>= 0.179~) but it is not going to be installed
                        Depends: network-manager-gnome (>= 0.9.8) but it is not going to be installed
                        Recommends: gnome-online-accounts (>= 3.25.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

pls help me, sorry my english....thxxx

**Comment by daniruiz** [comment]
Sorry dude :disappointed: but this issue has nothing to do with flat-remix-gnome. I can't help you with it
