### ISSUE TITLE
Debian 10 login css issue

### ISSUE THREAD

**Issue by hnariman** [daniruiz/flat-remix-gnome#127]
While installing on Debian 10 gdm3 (all defaults) maybe high res maybe an issue. But I'm more concerned of paths. Since background image of login screen didn't change, however input 

I'm happy to cooperate, however I don't know proper structure and files needed to be changed. I suggest changing CSS, I will try to commit it ASAP. 

Please check for screenshot
![20200204_123449](https://user-images.githubusercontent.com/31799546/73728176-49d4f080-474c-11ea-9b3d-a28e1e9f58e9.jpg)
 attached for further details

**Comment by daniruiz** [comment]
The theme is working fine on debian. That issue happens when the makefile doesn't properly find the login background. To fix it and recover the original gdm theme just reinstall gdm and gnome-shell
`sudo dnf reinstall gnome-shell gdm`
