### ISSUE TITLE
Latest release link

### ISSUE THREAD

**Issue by wachambo** [daniruiz/flat-remix-gnome#128]
I'd like to download your latest repo release via command line using the GitHub's API
[https://api.github.com/repos/daniruiz/flat-remix-gnome/releases/latest](https://api.github.com/repos/daniruiz/flat-remix-gnome/releases/latest)

To do this, I need you mark your latest release.
Do you think this can be useful for people like me who can't update via PPA, copr...?

Thanks and congrats for you work :)

**Comment by daniruiz** [comment]
Github treats tags as releases and that's why they are shown on the releases page. But for some reason, there are many things that work with releases that don't work with tags... for example the latest release, so I would need to manually create the releases
It's just not worth it
