### ISSUE TITLE
Gnome 3.36 update

### ISSUE THREAD

**Issue by clevioorlando** [daniruiz/flat-remix-gnome#130]
GDM and shell themes have some bugs on 3.36 :) but that's expected, as all themes do. The box sizes on GDM themes, box sizes on "password" prompt and some icons are too big. I guess that's about it. I'm running manjaro unstable with gnome 3.36.

**Comment by daniruiz** [comment]
I've been trying to update the theme to 3.36, but there are way too many changes. I think I'll have to start from the beginning, completely remaking the theme :sleepy:

**Comment by sp1ritCS** [comment]
> I think I'll have to start from the beginning, completely remaking the theme

Could you share your progress (maybe separate branch), I'd love to help you testing

**Comment by daniruiz** [comment]
Sure. I'll add a new branch and launch new releases as beta. I don't have as much time I used to for my projects, but I promise it this will be updated :wink:

**Comment by daniruiz** [comment]
I've seen the theme works good enough if it installed replacing the original gnome theme by running `make && sudo make install` and loging in with the Flat-Remix DE session
If you are using arch installing the `flat-remix-gnome` package from AUR is the same thing

**Comment by sp1ritCS** [comment]
> works good enough

As @clevioorlando said, the issues are primarily input boxes, popups (e.g for auth), some icons and the app overview.

Input boxes / Popup:
![image](https://user-images.githubusercontent.com/31540351/76340611-262d3900-62fc-11ea-9a33-121d1168966f.png)

Some Icons (The Settings):
![image](https://user-images.githubusercontent.com/31540351/76340828-80c69500-62fc-11ea-89c1-ad81ac2322a0.png)

The App Overview, just look at the grid I drawed in (marked the issues)
![image](https://user-images.githubusercontent.com/31540351/76341115-e31f9580-62fc-11ea-8714-ce8fa496c1ad.png)
I also managed to get two rows on top of each other (cant replicate right now)

And the Folders look messed up (cant screenshot), it just needs a background.

But the biggest issues are in gdm, as far as I have seen, The Password box now doesn't need so much top/bottom padding anymore, I'm not sure but that might fix the "back" arrow without doing anything.

**Comment by TheAifam5** [comment]
When I open Discord, the top bar of the gnome shell starts to flicker few times.

**Comment by daniruiz** [comment]
I've added a new 3.36 branch with the new changes: https://github.com/daniruiz/flat-remix-gnome/tree/3.36

Right now only light and dark variants are available (including the fullPanel variant) and it doesn't provide the theme for GDM

![image](https://user-images.githubusercontent.com/12565871/76681255-6426a780-65f1-11ea-962e-52018a7b616c.png)

**Comment by daniruiz** [comment]
New update!  

![image](https://user-images.githubusercontent.com/12565871/77161261-844ede80-6aa9-11ea-901f-1902c13383e9.png)  
![image](https://user-images.githubusercontent.com/12565871/77161342-b2ccb980-6aa9-11ea-91bf-281f0aa51989.png)  

![image](https://user-images.githubusercontent.com/12565871/77161295-96308180-6aa9-11ea-92ef-eb0d1f2e0cdc.png)

**Comment by raghav18gupta** [comment]
Has GNOME retarded or what. It breaks everything!

**Comment by daniruiz** [comment]
Another weekly update.
In general terms I removed the search result boxes and redesigned the login and lock screens. The theme can now be installed/uninstalled via `sudo make install` / `sudo make uninstall` which will add the gdm theme background. Right now it uses the default one and does not read your configured image, lets hope that works for the next update

Enjoy it :wink: 

![image](https://user-images.githubusercontent.com/12565871/77854061-28423380-71e8-11ea-8acb-53e853919193.png)

**Comment by zeparu** [comment]
just installed the new version from the aur, getting an error when trying to do the post-install stuff

```
/home/zepar/Bilder/Wallpaper/FFXIV/1af23a09b1cb6c563e69f2d142fe4ea046d7ad98_s2_n2.png
if [ 6 -le 1 ] ;\
then \
	cp -f "/home/zepar/Bilder/Wallpaper/FFXIV/1af23a09b1cb6c563e69f2d142fe4ea046d7ad98_s2_n2.png" src/gresource/login-background ;\
else \
	convert -scale 10% -gaussian-blur 0x6 -resize 1000% "/home/zepar/Bilder/Wallpaper/FFXIV/1af23a09b1cb6c563e69f2d142fe4ea046d7ad98_s2_n2.png" src/gresource/login-background ;\
fi
make -C src/gresource build
make[1]: Verzeichnis „/usr/share/flat-remix-gnome/src/gresource“ wird betreten
cp ../../Flat-Remix/gnome-shell/gnome-shell.css .
cp ../../Flat-Remix-Dark-fullPanel/gnome-shell/gnome-shell.css gnome-shell-high-contrast.css
sed "s/assets/resource:\/\/\/org\/gnome\/shell\/theme/g" -i *.css
glib-compile-resources gnome-shell-theme.gresource.xml
gnome-shell-theme.gresource.xml: »pad-osd.css« konnte im aktuellen Ordner nicht gefunden werden.
make[1]: *** [Makefile:11: build] Fehler 1
make[1]: Verzeichnis „/usr/share/flat-remix-gnome/src/gresource“ wird verlassen
make: *** [Makefile:11: all] Fehler 2
mkdir -p /usr/share/themes/
cp -r Flat-Remix-Dark-fullPanel Flat-Remix-Dark Flat-Remix-fullPanel Flat-Remix Flat-Remix-Miami-Dark-fullPanel Flat-Remix-Miami-Dark Flat-Remix-Miami-fullPanel Flat-Remix-Miami /usr/share/themes/
cp -r share/ /usr/
cp: der Aufruf von stat für 'share/' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:33: install] Fehler 1
Fehler: Befehl konnte nicht korrekt ausgeführt werden
:: Starte post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

```

**Comment by daniruiz** [comment]
Yes, sorry, I forgot adding the share directory :sweat_smile: 
It is fixed now, you'll probably need to remove the package from yay's cache `~/.cache/yay` and then reinstall it.

**Comment by daniruiz** [comment]
New update changes
 * Add Miami variants
 * Improve searchbar design
 * Use current background image as gdm background
 * updated aur repo

![image](https://user-images.githubusercontent.com/12565871/78506009-6060ed80-7777-11ea-8aca-ba4b3fceb5df.png)

**Comment by daniruiz** [comment]
@zeparu I didn't notice the 'missing pad-osd.css' error, it was due to the .gitignore configuration, sorry again. It is also fixed now :wink: 
Thanks for the warning
