### ISSUE TITLE
Errors were encountered while processing:  flat-remix-gnome

### ISSUE THREAD

**Issue by aminraeisi** [daniruiz/flat-remix-gnome#131]
OS: Ubuntu 18.04
GNOME: 3.28.2

I tried to install the theme using the commands:
```
sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt-get update
sudo apt-get install flat-remix-gnome
```

but the last command gives me this error:
```
/var/lib/dpkg/info/flat-remix-gnome.postinst: 4: /var/lib/dpkg/info/flat-remix-gnome.postinst: make: not found
dpkg: error processing package flat-remix-gnome (--configure):
 installed flat-remix-gnome package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 flat-remix-gnome
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

And the bigger problem is that I cannot install anything now and I get this error:
```
Errors were encountered while processing:  flat-remix-gnome
```

or sometimes:
```
W: APT had planned for dpkg to do more than it reported back (870 vs 874).
   Affected packages: flat-remix-gnome:amd64
```

is there a way to solve this or remove the things that got installed so that I don't need to reinstall ubuntu?

**Comment by daniruiz** [comment]
The error is telling you don't have make installed
Just in case, install all the dependencies
`sudo apt install make, libglib2.0-dev-bin, imagemagick`

You are using
