### ISSUE TITLE
no search icons in gnome desktop search with flat-remix installed

### ISSUE THREAD

**Issue by millerthegorilla** [daniruiz/flat-remix-gnome#133]
Hi, I have installed flat-remix from the standard fedora repositories (I have rmpfusion repos installed as well), and when I search for an application I find that there are no icons showing at all.
Because I installed from standard repos, do I need to file a bugzilla report?

**Comment by daniruiz** [comment]
Can you provide a screenshot?

**Comment by millerthegorilla** [comment]
yh, hang on and I will.  But its only when I log in using the flat-remix option as a desktop choice.  When I am on Gnome, it works as expected.

**Comment by millerthegorilla** [comment]
https://paste.pics/a913fcb96c464dec44b1b1a1abf4e5c9

**Comment by millerthegorilla** [comment]
if I type gimp, and then hit enter, gimp opens, so the search functionality is working, but the icons aren't appearing.

**Comment by millerthegorilla** [comment]
I've tried using different icon themes, but no luck.  It all works ok if I log back in using the Gnome desktop, even the flat remix theme and icons.

**Comment by millerthegorilla** [comment]
it occurs to me that perhaps I need to install appropriate icon theme?

**Comment by millerthegorilla** [comment]
although, when I hit enter, there is a brief glimpse of the icon before the program launches.

**Comment by daniruiz** [comment]
I'm sorry but I can't help here. The theme can't directly hide the results so this must be gnome's fault
