### ISSUE TITLE
Can't change the login screen wallpaper

### ISSUE THREAD

**Issue by GianlucaRea** [daniruiz/flat-remix-gnome#134]
Hi I can't change the wallpaper icon by the "sudo make && sudo make install command" as described in the web site of the theme.
I attach the terminal screenshot of the execution of the command 

![Screenshot from 2020-03-26 11-38-09](https://user-images.githubusercontent.com/43826151/77637674-4e50a500-6f56-11ea-9db1-a9947a55e266.png)
![Screenshot from 2020-03-26 11-38-05](https://user-images.githubusercontent.com/43826151/77637677-4f81d200-6f56-11ea-8248-37458daee987.png)

**Comment by daniruiz** [comment]
go to ~/.local/share/backgrounds and remove the space from the background name. The script was updated to fix that issue for files with spaces in their names but I don't know why it isn't working for you.

Try it and let me know if it fixes it ;)

**Comment by GianlucaRea** [comment]
It works!!!
 Thanks for the quick response!
