### ISSUE TITLE
How to fix this prompt?

### ISSUE THREAD

**Issue by ibaka9** [daniruiz/flat-remix-gnome#135]
![2020-03-30 03-51-43 的屏幕截图](https://user-images.githubusercontent.com/17043012/77859112-19846c80-723a-11ea-90da-532256a4ca8f.png)

I am using Flat-Remix-Dark shell theme.

**Comment by daniruiz** [comment]
Which version of gnome-shell and flat-remix-gnome are you using?

**Comment by ibaka9** [comment]
I'm using older gnome-shell, my bad....
by the way, i am using GNOME Shell 3.28.4 and the latest flat-remix-dark(20200329-beta (GNOME 3.36))
