### ISSUE TITLE
Multiple font issues in the last update

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix-gnome#138]
Hi, I'm using your gnome theme for a long time. I love it. I updated it now and I found multiple issues as you can see in the pictures below:

**1. Notifications: (screenshot looks better that reality)**
![Screenshot from 2020-04-13 15-02-22](https://user-images.githubusercontent.com/36289254/79123931-8ac83180-7d9b-11ea-9e7a-6721094853a4.png)

**2. Lock Screen: almost invisible clock and notifications**
![20200413_150820](https://user-images.githubusercontent.com/36289254/79123975-a29fb580-7d9b-11ea-8a84-a07c921a68ea.jpg)

**3. Login Screen: cancel button font invisible and avatar looks bad depending background color**
![20200413_151822](https://user-images.githubusercontent.com/36289254/79124060-d11d9080-7d9b-11ea-9ae7-fa4fd7536605.jpg)

OS: Debian 10 (Buster).
GNOME Shell 3.30.2.

I hope it helps. 

Kind regards

**Comment by Dvlnst** [comment]
Sorry, I had a script to automatically update your theme to the current master but I didn't notice master only works for Gnome 3.36 now. Installing version 20191116 works fine again.

Kind regards.

**Comment by daniruiz** [comment]
No problem :wink:
Thanks for reporting it anyway
