### ISSUE TITLE
Broken lockscreen

### ISSUE THREAD

**Issue by ColinEspinas** [daniruiz/flat-remix-gnome#139]
Hello, I have something weird happening, after installation my login screen works as expected (general login screen at start) but my lockscreen (session specific) is completly broken, I've also tried to put my shell theme back to default but it is completly broken now.

I don't know what to do to change that and make that lockscreen theme works, I'm on Manjaro, Gnome 3.36.1.

PS: The shell theme is working, the only thing not working is the lockscreen.

**Comment by jonasotow** [comment]
Hello, I have the same mistake. 
I'm Pop OS 18.04 LTS Gnome 3.28.2

**Comment by daniruiz** [comment]
Hi!

**Comment by emalamisura-c2m** [comment]
Its 100% broken on the latest version of Ubuntu.

**Comment by daniruiz** [comment]
@emalamisura-c2m the latest version is completely rebuilt for the new ubuntu 20.04. Are you sure you installed the correct version? which version of ubuntu are you using? Which version of the theme?

**Comment by daniruiz** [comment]
Just tested the new release and everything works fine. Try reinstalling gnome-shell and installing Flat-Remix again with this new version :wink: 
`sudo pacman -S gnome-shell`
I close the issue but write me here if it still does not work :wink:

**Comment by emalamisura-c2m** [comment]
Works, and gnome-software is themed now as well.  So all is well.
