### ISSUE TITLE
Remove borders on popup windows

### ISSUE THREAD

**Issue by mfauvain** [daniruiz/flat-remix-gnome#140]
Hi, thx for this nice theme. How can I remove the almost transparent border on the popup menus?
Looked into the gnome-shell.css and tried to modify some, but no luck.
thx

**Comment by mfauvain** [comment]
Ok found it. Had to actually recompile with glib-compile.

**Comment by daniruiz** [comment]
Awesome! :wink: 
Can this issue be closed then?

**Comment by mfauvain** [comment]
sure. One quick question though, lock screen (and unlock, password input etc) do take into account my modifications in gnome-shell.css. However the login screen (initial screen) does not. Any obvious thing I am missing?

**Comment by daniruiz** [comment]
The login screen uses a compiled version of the theme. If you want to modify it too you can follow this quick guide:
1. download / clone this repository
1. Install imageMagick and libglib2:
Debian
`sudo apt install libglib2.0-dev-bin`  
Fedora  
` imagemagicksudo dnf install glib2-devel ImageMagick`  
Arch  
`sudo pacman -S glib2 imagemagick`
1. Modify the code inside https://github.com/daniruiz/flat-remix-gnome/tree/master/src/sass
1. Regenerate and reinstall the theme, running `make build && sudo make install` from the projects root directory
