### ISSUE TITLE
Inaccessible text colours and icons on top panels and notifications

### ISSUE THREAD

**Issue by paulpopus** [daniruiz/flat-remix-gnome#141]
I'm using the latest shell theme from April 12st with the filename `03-Flat-Remix-Dark_20200412` from https://www.pling.com/p/1013030 .

I am on Ubuntu 19.10 with `GNOME Shell 3.34.3`

There are a couple of icons and labels that don't have great contrast I've screenshoted below.

This is how a notification looks like when it pops up
![Screenshot from 2020-04-17 19-09-35](https://user-images.githubusercontent.com/35137243/79600863-bf135900-80df-11ea-9623-9ca350c0848d.png)

And this is how it looks like when you hover over it
![Screenshot from 2020-04-17 19-10-29](https://user-images.githubusercontent.com/35137243/79600851-b91d7800-80df-11ea-9780-98eea5f9dbb7.png)
With its contents being completely unreadable

This is how the default shell theme looks like for reference
![Screenshot from 2020-04-17 19-16-49](https://user-images.githubusercontent.com/35137243/79601006-0699e500-80e0-11ea-9e33-174e3f4ba2dd.png)

Similar issues are present in the power dropdown but only with the icons
![Screenshot from 2020-04-17 19-08-21](https://user-images.githubusercontent.com/35137243/79601039-1285a700-80e0-11ea-8881-9d7d5aaf79c6.png)

And I also notice it in the top modal panel
![Screenshot from 2020-04-17 19-19-29](https://user-images.githubusercontent.com/35137243/79601348-9344a300-80e0-11ea-98a9-55c5fa8ae904.png)

Reference
![Screenshot from 2020-04-17 19-07-26](https://user-images.githubusercontent.com/35137243/79601363-96d82a00-80e0-11ea-863c-c48e968687f9.png)

And in the open weather map, but I don't know if this issue is with the widget or not
![Screenshot from 2020-04-17 19-19-38](https://user-images.githubusercontent.com/35137243/79601281-7a3bf200-80e0-11ea-9eb8-96783f789e10.png)

Reference
![Screenshot from 2020-04-17 19-07-19](https://user-images.githubusercontent.com/35137243/79601335-8f188580-80e0-11ea-8295-45e4ebe73db7.png)

I hope this helps but let me know if I can provide more information. Thanks a lot for the theme it's really nice overall.

**Comment by paulpopus** [comment]
I just noticed it on the shutdown modal too
![Screenshot from 2020-04-17 19-23-11](https://user-images.githubusercontent.com/35137243/79601627-04845600-80e1-11ea-8d4d-35f22a859d5c.png)

Reference
![Screenshot from 2020-04-17 19-23-30](https://user-images.githubusercontent.com/35137243/79601645-09490a00-80e1-11ea-833e-0ff2c32b584e.png)

**Comment by daniruiz** [comment]
The latest theme is for GNOME 3.36 only
You need to install the theme for GNOME 3.34 and earlier :wink: 
![image](https://user-images.githubusercontent.com/12565871/79615546-5d64e600-8103-11ea-804d-cc870c5e7a57.png)

**Comment by paulpopus** [comment]
Ohh my bad, that's embarrassing.

**Comment by daniruiz** [comment]
don't worry :smile: It's a normal mistake
