### ISSUE TITLE
The icons in tray like extensions have no shadow . 

### ISSUE THREAD

**Issue by SimonWann** [daniruiz/flat-remix-gnome#142]
I have tried 'trayiconplus' and 'trayicons:reloaded' gnome exensions.They can show the application icons when those application run in backstage . When I use flatremix shell ,all of icons show no shadow .Beside , the no-extensions appicons like telegram , flameshot,etc... just show a very white square .

**Comment by daniruiz** [comment]
Could you provide a screenshot?

**Comment by daniruiz** [comment]
Not an issue
