### ISSUE TITLE
[dash-to-dock] Weird 1px white border

### ISSUE THREAD

**Issue by TheAifam5** [daniruiz/flat-remix-gnome#143]
Hey,

I made an update today to commit 5e7288d12a369c8fa2876046a3a927d517a92a8a and the white 1px border appeared. Does not match with the look of the "noborders" themes.

![image](https://user-images.githubusercontent.com/2192274/80096975-c8cb0f80-856a-11ea-94be-2434cc912e9f.png)

**Comment by daniruiz** [comment]
Hey! Thanks for reporting :wink: 
I think that border fixes with the latest dash to dock update. Anyway I know how to remove that border and I'll change it for next update
