### ISSUE TITLE
Crash GDM3 Ubuntu 20.04

### ISSUE THREAD

**Issue by BlueGarm** [daniruiz/flat-remix-gnome#144]
This morning I installed the new version of Ubuntu 20.04 (Final Version). And after, when I try to install the Flat Remix Gnome, I can't load the system because I have a fatal error with gdm3.
So, to restore the system I have to login with TTY and enter the following command to select the Yaru default ubuntu gdm :
`sudo update-alternatives --config gdm3-theme.gresource`

This bug is weirder because, on my previous install of 20.04 (Developpement build) i don't have this bug, everything works perfectly.

Thanks for yours amazing jobs, and sorry for my terrible English...

**Comment by daniruiz** [comment]
Weird, I've tested it again on the final Ubuntu 20.04 release and it worked fine :thinking:
Did you try completely reinstalling it? GDM doesn't really support themes, so it is too delicate to modify :cry:

**Comment by BlueGarm** [comment]
Thanks, I deleted it and remove the foler Flat-Remix-Gnome in /usr/share/ and after a reboot I reinstalled with the commands on your blog : 
`sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt update
sudo apt install flat-remix-gnome`

Finally after a last reboot it's working ! 😘 

Sometimes the simple way is the best way... 🤦
