### ISSUE TITLE
Pop-up Window UI background is not set properly

### ISSUE THREAD

**Issue by darrenjkt** [daniruiz/flat-remix-gnome#145]
Just want to say that I love your theme so much. Everything looks super sleek and beautiful. There is one UI bug I noticed though.

![Screenshot from 2020-04-29 21-54-54](https://user-images.githubusercontent.com/39115809/80593231-2deb9d00-8a64-11ea-917e-cd0b4aa77fb9.png)

![Screenshot from 2020-04-29 22-25-56](https://user-images.githubusercontent.com/39115809/80595652-71e0a100-8a68-11ea-9db8-3fd1bdb4e84e.png)

Same happens with the shutdown/restart window

As can be seen in the screenshots, the text protrudes from the background and so does the textfield. How can I resolve this?

**Comment by fdinardo** [comment]
which gnome-shell version are you using?

**Comment by darrenjkt** [comment]
I'm on GNOME Shell 3.28.4

**Comment by daniruiz** [comment]
Common mistake :wink:, easy fix

For gnome-shell < 3.36
![image](https://user-images.githubusercontent.com/12565871/80648114-e23ef080-8a6f-11ea-970b-174297c2f308.png)

Here is the link: https://github.com/daniruiz/flat-remix-gnome/tree/20191116

**Comment by darrenjkt** [comment]
Is there a way to get back the colour scheme of my above screenshots for the popup windows? 

![Screenshot from 2020-04-30 07-32-28](https://user-images.githubusercontent.com/39115809/80649119-c6aa0900-8ab4-11ea-89fa-a3080836eb79.png)

**Comment by daniruiz** [comment]
Sorry, but I can't provide updates for every gnome version. If you prefer the new theme you'll need to update to gnome 3.36

**Comment by darrenjkt** [comment]
That's okay, I understand. 

Do I edit under the /* Modal Dialogs */ section in the gnome-shell.css if I want to change the colours?

**Comment by daniruiz** [comment]
I'd suggest to clone the repo and modify the colors.scss file
https://github.com/daniruiz/flat-remix-gnome/blob/20191116/src/sass/gnome-shell-sass/_colors.scss

You need scss installed. And then you can rebuild it with the src/build.sh script `./build.sh -r`
