### ISSUE TITLE
Missing Appearance tab on Ubuntu 20.04

### ISSUE THREAD

**Issue by CiliaFred** [daniruiz/flat-remix-gnome#146]
Hi, in parameters with ubuntu 20.04, the new tab appearance doesn't appear with flat-remix theme.

With Yaru theme :
![image](https://user-images.githubusercontent.com/1827520/80946678-dc8a3780-8dee-11ea-99d9-940ca5d0a78f.png)

With Flat Remix theme : 
![image](https://user-images.githubusercontent.com/1827520/80946720-f297f800-8dee-11ea-81b0-238d8ae8fc95.png)

**Comment by pmwisse** [comment]
Same here! Don't know whether it is significant, but this is an upgraded install of Ubuntu, so I was on 19.10 before.

**Comment by CiliaFred** [comment]
It's significant, because we can't enable ubuntu dark mode :)

**Comment by daniruiz** [comment]
The appearance menu has no purpose if you are not using ubuntu's default themes
Use gnome tweaks instead
