### ISSUE TITLE
Ubuntu Software windows is transparent using Flat Remix on Ubuntu 20.04

### ISSUE THREAD

**Issue by pmwisse** [daniruiz/flat-remix-gnome#147]
The app 'Snap shop' as it is now called in my install, is transparent. 

![Schermafdruk van 2020-05-14 12-14-04](https://user-images.githubusercontent.com/48717736/81922462-723a7980-95dc-11ea-84c7-270d3178b040.png)

**Comment by pmwisse** [comment]
Apps like 'Update management' or 'Synaptic' or 'Software & Updates' work normally.

**Comment by daniruiz** [comment]
Ubuntu has replaced many apps with snaps, and snaps are a great idea, but their desktop integration.... There is no way I could fix this, I would have to make a snap version of the theme, but I don't have time for right now.
If you like the theme I suggest you using the usual packages, just with `apt` and remove the snap ones (`snap list` `snap remove <app>`)

**Comment by pmwisse** [comment]
Thanks for your reply, but I'm not sure it is correct. As far as I know, I do not use snaps for installing the flat remix theme, because I get them from your repository. And I do not see how using software as a snap would lead to the Snap store to appear as a fully transparent window using the flat remix theme. My problem with the Ubuntu Software store is that its piece of software renders as a completely transparent window when I use your theme.

**Comment by daniruiz** [comment]
I mean, most of the apps on Ubuntu are snaps now, not my theme, and snaps don't work well with themes.
Try running `snap list` for example and you'll see all the snap packages ubuntu installs by default

Ubuntu added its own theme as a snap, so that it works properly for its own apps.

**Comment by elucidsoft** [comment]
This really needs to be fixed since ALOT of stuff is Snap based now this theme is problematic to use on Ubuntu.

**Comment by daniruiz** [comment]
Then open an issue for snaps. Why should the theme be installed as a snap, that doesn't make any sense
