### ISSUE TITLE
Fonts not applied correctly

### ISSUE THREAD

**Issue by MariuszSzlachta** [daniruiz/flat-remix-gnome#148]
After update from Ubuntu 19.10 to 20.04 there is a problem with fonts on top panel and some other places in the shell.

In styles font are not defined using font-family, and weird font is applied to the shell. Even if I change my system fonts, theme looks broken.
![Zrzut ekranu z 2020-05-17 14-06-29](https://user-images.githubusercontent.com/31552338/82145123-ebd69f80-9848-11ea-89a5-c078dd5a217d.png)

**Comment by daniruiz** [comment]
The theme uses the system's fonts so if you want to change it you can do so by opening gnome-tweaks -> Fonts and changing the interface font.
