### ISSUE TITLE
Login background gets replaces without installing custom login

### ISSUE THREAD

**Issue by creativiii** [daniruiz/flat-remix-gnome#149]
First of all, love the new look for 20.04.

I installed the shell theme, gtk and icon pack, however my login screen background got switched to the usual one with the waves.

Any way to not have this happen?

**Comment by daniruiz** [comment]
Just install it again. When gnome-shell is updated the theme is replaced. I could program some triggers but if gnome pushes lots of changes to a new version if my theme isn't compatible it would automatically break the desktop :sweat: 
Hope that helps :wink:
