### ISSUE TITLE
Current build configration is broken

### ISSUE THREAD

**Issue by tim77** [daniruiz/flat-remix-gnome#150]
Hello. Current build result is look like this:

```
/usr/share/flat-remix-gnome:

Flat-Remix/
Flat-Remix-Dark/
Flat-Remix-Darkest/
Flat-Remix-Darkest-fullPanel/
Flat-Remix-Dark-fullPanel/
Flat-Remix-fullPanel/
Flat-Remix-Miami/
Flat-Remix-Miami-Dark/
Flat-Remix-Miami-Dark-fullPanel/
Flat-Remix-Miami-fullPanel/
Makefile
share/
src/
```

This is a real mess:
- Source files shouldn't installed on users machines.
- Makefile shouldn't installed on users machines.
- What in `share/` folder? This is not proper place for it seems like.

We MUST fix this somehow if we want to see new updates in official Linux repositories and if we want have not broken themes.

**Comment by daniruiz** [comment]
Hi!
If you want to use only one theme you can just download it and place it on /usr/share/themes. But GDM's theming isn't a "theme" it completely overrides the existing .gresource file with a patched one. So:
1. This package will never arrive to official repositories because its hacky, unreliable, and there is no better way of doing it because GDM does not support theming.
2. The theme needs to be recompiled every time you change your background image, so yes... you do need to have the source code of the theme in order to update your login screen's wallpaper

So now that you understand how this theme works I'm open to suggestions for improvements :wink:

**Comment by tim77** [comment]
> This package will never arrive to official repositories

It's already here for a long time. 😃 At least in Fedora repos. And it's great theme. But now nothing works after update without manual intervention and i got stuck a little bit here with update due to lack of time. But hope we can fix this soon anyway.

**Comment by daniruiz** [comment]
Are you talking about my copr package, or about the other package that I don't maintain?

**Comment by tim77** [comment]
- https://src.fedoraproject.org/rpms/gnome-shell-theme-flat-remix
- https://bodhi.fedoraproject.org/updates/?packages=gnome-shell-theme-flat-remix

**Comment by daniruiz** [comment]
I don't know how that one is packaged
You can try with my copr one
```
sudo dnf copr enable daniruiz/flat-remix
sudo dnf install flat-remix-gnome
```

**Comment by tim77** [comment]
Sorry, don't get me wrong, but this COPR everyone should avoid and never use it. There was already reports from users which have broken system and can't log in because of broken GDM.

Can you please add build option which allow install `flat-remix-gnome` in proper location and at least we will have working GNOME Shell theme here?

**Comment by daniruiz** [comment]
Well the COPR was for people that do want the login theme, even with the possible consequences. Some versions were unstable, as somethings aren't the same for all distros, and that gave me some headaches :sweat: But it does work now on ubuntu, fedora and arch.
Fixing the login isn't that hard any way, you only need to reinstall the gnome-shell package

Anyway, for the official package on Fedora, I would just copy the themes, not the GDM part, so you don't need:
```
 BuildRequires:  dconf
 BuildRequires:  glib2-devel
 BuildRequires:  ImageMagick+
```
Also, everything inside share is intended for ubuntu especially, as it is the easiest way to override Yaru theme. So you can ditch that too

So the only thing the installer needs to do is `cp Flat-Remix* /usr/share/themes/`

Thanks for maintaining the package anyway :+1:

**Comment by tim77** [comment]
@daniruiz thank you. Built and pushed to repos. Now [on QA](https://bodhi.fedoraproject.org/updates/FEDORA-2020-c496bd32da) and you can give +1 karma to update and users will receive this update tomorrow and will not wait for 8 days. 😊

**Comment by daniruiz** [comment]
Awesome, I'll recommend this package in case the user only wants the shell themes, and publish it on twitter tomorrow
Thank you again :wink:

**Comment by daniruiz** [comment]
Hello there! :wink:
Recently I've added extra color variants to the theme, so I write you to ask if you could update the package for Fedora.

**Comment by tim77** [comment]
Hi! Done: [F32](https://bodhi.fedoraproject.org/updates/FEDORA-2020-e078d6a50c), [F31](https://bodhi.fedoraproject.org/updates/FEDORA-2020-9e81ab977f).

Also i setup [Anitya](https://release-monitoring.org/project/28322/) service for this, but ping me anytime!

**Comment by daniruiz** [comment]
Awesome! :heart: Thank you!
