### ISSUE TITLE
Build Shell Script Missing?

### ISSUE THREAD

**Issue by ndmax** [daniruiz/flat-remix-gnome#152]
Has `src/build.sh` been intentionally removed?  After pulling the most recent updates, I went to update the login screen and it doesn't appear to be included in the master branch.

**Comment by daniruiz** [comment]
Everything was moved to the 'root' Makefile, as the theme was completely redesigned for gnome 3.36
If you need that file here is the release for gnome 3.34 https://github.com/daniruiz/flat-remix-gnome/tree/aaa4b18c5ba2c9d8c20e1c2afcead9f712350be0
