### ISSUE TITLE
Crashing on Ubuntu 20.04

### ISSUE THREAD

**Issue by trajber** [daniruiz/flat-remix-gnome#153]
I installed flat remix theme as a package using ppa:daniruiz/flat-remix on Ubuntu 20.04 and after an upgrade it is failing on startup. However, if I select any other theme on login screen, gnome loads correctly.
Let me know how to debug this issue to provide you more information about it.

Thanks

**Comment by daniruiz** [comment]
Hi!
Could you provide some screenshots? I'm not sure what you mean by 'failing on startup'

**Comment by poobal** [comment]
I believe I am having the same issue too. Fresh install of 20.04 and theme installed via ppa. When I login using flat-remix option I get this https://photos.app.goo.gl/jmy7vyha4m1rR1zTA 

My syslog dump is [here](https://drive.google.com/file/d/1VxpwJ3teNmVdoGuPld5xdWSEUfhzMcvb/view?usp=sharing)
I captured logging out of default (ubuntu) and logging back selecting Flat-remix and encountering the crash. Then logging out and logging back in using the default (ubuntu) theme. 

Jun 23 22:47:46 cartman gnome-shell[14819]: JS ERROR: Error: No valid stylesheet found for 'Flat-Remix/gnome-shell.css'#012loadTheme@resource:///org/gnome/shell/ui/main.js:433:15#012_loadDefaultStylesheet@resource:///org/gnome/shell/ui/main.js:378:5#012_initializeUI@resource:///org/gnome/shell/ui/main.js:175:5#012start@resource:///org/gnome/shell/ui/main.js:146:5#012@<main>:1:47 

I am not sure if this is what's causing it to crash. 

I am running this on Hades Canyon Nuc with i7-8705G with AMD VegaM + Intel HD 630 running xorg.

**Comment by daniruiz** [comment]
Ooh. I've found the issue, the Flat-Remix session is pointing to `/usr/share/themes/Flat-Remix`  but the theme is now named Flat-Remix-Blue.
You can fix this manually by editing `/usr/share/gnome-shell/modes/flat-remix.json` and replacing `Flat-Remix` with `Flat-Remix-Blue`. I've pushed the fix to the package too so it should be available soon.

Thanks for reporting it :wink:
