### ISSUE TITLE
Wrong Login Background?

### ISSUE THREAD

**Issue by Shiroukoji** [daniruiz/flat-remix-gnome#154]
I've installed the AUR package with pamac and I only get the picture within the package as login background not my own setted wallpaper. Was there a change in the package? Last time I installed the package with yay it worked. Pamac works from /tmp directory instead from a subdirectory of home like yay. Is there anything I have to notice? The process itself doesn't give me any errors. The other parts of the theme working perfectly! Thanks for your work!

Cheers,
Shiroukoji

**Comment by daniruiz** [comment]
Hi!
The script gets the wallpaper from `dconf read /org/gnome/desktop/background/picture-uri`. Some gnome wallpapers are actually .xml files so they are not supported. Try using another login background and installing it again

**Comment by Shiroukoji** [comment]
I understand it, but I don't changed my wallpaper. I only switched to pamac from yay and updated to the new version of the package. I try to do it manually with make. Thanks for answering,

**Comment by daniruiz** [comment]
So you mean that it works with yay but it doesn't with pamac?

**Comment by Shiroukoji** [comment]
Yeah that seems the problem, I actually don't know why, but yay and manual with make command works

**Comment by daniruiz** [comment]
Just tried it and I can confirm it doesn't work with pamac :cry: 
Pamac is executed with root privileges via pkexec, wich, for security reasons, only exposes the following env variables: 
```
SHELL=/bin/zsh
LANG=es_ES.UTF-8
TERM=xterm-256color
COLORTERM=truecolor
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
LOGNAME=root
USER=root
HOME=/root
PKEXEC_UID=1000
```
So the install script is unable to identify the user installing the package. Thus, dconf can only read the wallpaper set for the root user.
I've pushed a patch that uses the user with uid 1000 as a workaround, as the user 1000 is usually the first user created on linux.

**Comment by daniruiz** [comment]
Seems it is working now :+1: 
Thanks for reporting it :heart:
