### ISSUE TITLE
Small font and bar shifted to right on hi dpi screen

### ISSUE THREAD

**Issue by MuathAmer** [daniruiz/flat-remix-gnome#155]
As seen in the attached screenshot, the font is very small, I would want it to be as large as the word "Google" on the opened chrome tab, I tried to change the css but it was very unpractical because there is so many font-size properties, and I need the shell theme to increase the font scale everywhere in the shell, including the notifications & calendar pane and the settings menu on the right.

Also, for some reason, the whole shell bar is just shifted to the right as seen, this screenshot is fullscreen wide.

And while at it, how can I change the transparency darkness of the bar?

![Screenshot 2020-06-23 20:28:49](https://user-images.githubusercontent.com/7873900/85435571-4ec9fd80-b590-11ea-94ef-126d3c408c02.png)

**Comment by daniruiz** [comment]
At the begining of the css file you can see the global font-size value:
```
stage {
  font-size: 10pt;
  color: #5c616c; }
```
The title bar is shifted due to the panel blur extension you use

To change the panel's transparency, find the #panel selector (around line 2241)  and modify the background
