### ISSUE TITLE
stage.font-size property doesn't apply to calendar font size

### ISSUE THREAD

**Issue by MuathAmer** [daniruiz/flat-remix-gnome#157]
The `stage.font-size` property seems to apply to everything but the shell calendar.
The font size of the calendar stays the same when changing `font-size` of `stage`, which is very small in hidpi monitors.

And thanks for the amazing theme :D

**Comment by daniruiz** [comment]
Then you'll need to modify `flat-remix-gnome/src/sass/gnome-shell-sass/upstream/gnome-shell-sass/_common.scss` and set `$base_font_size` back to 11

To rebuild the theme you need to install scss and run `make build`
