### ISSUE TITLE
Show applications in gnome menu not scrolling after apply this theme

### ISSUE THREAD

**Issue by diego98martins** [daniruiz/flat-remix-gnome#158]
I use Ubuntu 20.04 and I like so much using this theme. However, It doens't work exactly well in this new version of Ubuntu.

I've used temporaries solutions such as `gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false` or apply another shell theme, but I would like to use your theme.

I've founded the same problem but no relationated to this theme in this [link](https://askubuntu.com/questions/1236559/show-applications-not-scrolling-after-upgrade-to-ubuntu-20-04-from-18-04-via-19)

**Comment by daniruiz** [comment]
Sorry but that seems like an issue of the dash-to-dock extension. The theme only changes the appearance but not the behavior of the shell.

I'll close this for now, but feel free to comment here with more info.
