### ISSUE TITLE
Calandar colour not applied

### ISSUE THREAD

**Issue by StoneMonarch** [daniruiz/flat-remix-gnome#159]
Gnome Version: 3.36.3
Ubuntu Version: 20.04 LTS
Shell: Flat-Remix-Dark-fullPanel (Latest version)

Fresh install of Ubuntu 20.04 LTS  with a few extensions. Issues persisted with and without extensions enabled. Calendar theme not being applied.

![Screenshot from 2020-07-14 12-35-16](https://user-images.githubusercontent.com/35647358/87455430-703c6900-c5d3-11ea-9190-c4ed843bae1f.png)

**Comment by daniruiz** [comment]
Seems like you are using an old version of the theme with the new gnome-shell 3.36

**Comment by StoneMonarch** [comment]
I downloaded from Pling and it appears to only have v3.34 versions on there. Cloned the GitHub repo and and worked perfectly. 

Thanks for the response

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/87468456-f4194400-c619-11ea-9e92-64840712d8c7.png)

Yes, that package is meant only for gnome <3.34
