### ISSUE TITLE
Bug on the shutdown screen

### ISSUE THREAD

**Issue by alissonlf** [daniruiz/flat-remix-gnome#160]
> In **Debian 10**, there is this small _error_:

![Captura de tela de 2020-07-22 20-15-58](https://user-images.githubusercontent.com/7702014/88238831-200b7980-cc59-11ea-97c3-821fd5270881.png)

**Comment by daniruiz** [comment]
You are using the wrong theme. You are using the theme for gnome 3.36, and you need the one for gnome < 3.34
My fault, it was not properly explained on the website. I've fixed the 'install' explanation
![image](https://user-images.githubusercontent.com/12565871/88266559-ae224700-cccf-11ea-9da1-a4281a1e4ecf.png)
