### ISSUE TITLE
Themes not appearing on gnome-tweaks after installing via apt repository

### ISSUE THREAD

**Issue by felixjb** [daniruiz/flat-remix-gnome#161]
I installed the package on my computer via the apt repository for Ubuntu but it is not appearing on gnome-tweaks application.

```
sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt update
sudo apt install flat-remix-gnome
```

OS: Ubuntu 20.04 LTS

**Comment by Nkr1shna** [comment]
I have the same issue.

**Comment by felixjb** [comment]
Nice! That worked for me! Thanks

**Comment by kellina** [comment]
Thanks, @Nkr1shna. I was with the same problem and I get fixed after I installed the package flat-remix-gtk
