### ISSUE TITLE
Issue with Login Screen

### ISSUE THREAD

**Issue by rrnicolay** [daniruiz/flat-remix-gnome#162]
Hi! 
Firstly I just want to say: Good job guys! Especially to daniruiz! What an excellent work! Thank you!
I used Flat Remix in Ubuntu 18.04 without problems. But now I'm on 20.04 and...
I've installed Flat Remix theme through make && make install. Except by the login theme, everything is working fine.
The login theme seems the official from ubuntu 20.04, with a blurred background image.
When I click on the lower right button (change the GUI or user, I don't know), another login screen appears (the purple gnome theme).
I can still login from any of the two login screens. Don't know what I messed up to reach this point. I do not even think this is a bug, probably I made something wrong. Is there something to try to fix this?
I would like to use the current background set by Variety in the login screen as well. Is it possible?
Thanks in advance.
![IMG_20200813_103524](https://user-images.githubusercontent.com/47363858/90147571-badb0d80-dd58-11ea-9743-b1870a86719d.jpg)
![IMG_20200813_103536](https://user-images.githubusercontent.com/47363858/90147581-bc0c3a80-dd58-11ea-99b7-d511f33d0007.jpg)
![IMG_20200813_103557](https://user-images.githubusercontent.com/47363858/90147587-bd3d6780-dd58-11ea-8396-21002c685603.jpg)

**Comment by daniruiz** [comment]
Hi there! Thanks for the nice feedback :wink:
I've just installed the theme on ubuntu and it is working fine for me.

Could you try to install it from the ppa repository?
```
sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt update
sudo apt install flat-remix-gnome
```

**Comment by rrnicolay** [comment]
I made a mess tweaking themes! Don't know how to fix this.
I removed my installation with "sudo apt-get remove flat-remix-gnome" (a warning appeared about /usr/share/flat-remix-gnome/src/gresource not being empty) and did the steps you suggested.
Same thing happens! On startup:
![original_da5d2756-e3b5-4518-ac37-6454cf6c796d_PXL_20200926_002658479 _exported_201_1601081063653](https://user-images.githubusercontent.com/47363858/94326173-bff6c380-ff78-11ea-87f5-16df6f836a56.jpg)
When I lock or resume the system(I can login normally from this screen):
![PXL_20200926_002812488](https://user-images.githubusercontent.com/47363858/94326205-f03e6200-ff78-11ea-8b04-5b21801249cc.jpg)
When I click on the botton right button to change the user, this login screen appears(the same one from startup):
![PXL_20200926_002836024](https://user-images.githubusercontent.com/47363858/94326509-a2c2f480-ff7a-11ea-9e98-9721a26f3fd1.jpg)
The login screen theme is inside the "flat-remix-gnome" theme as well? I tought I had to install with clone and make install.

**Comment by daniruiz** [comment]
Yes, the gdm theme is included with flat-remix-gnome package if you install it via ppa.

If the theme is properly install try running `sudo update-alternatives --config gdm3-theme.gresource`. There you should be able to select the flat-remix theme

**Comment by rrnicolay** [comment]
The output of `sudo update-alternatives --config gdm3-theme.gresource`:

`sudo update-alternatives --config gdm3-theme.gresource
[sudo] password for user: 
There are 3 choices for the alternative gdm3-theme.gresource (providing /usr/share/gnome-shell/gdm3-theme.gresource).

  Selection    Path                                                                       Priority   Status
------------------------------------------------------------
  0            /usr/share/themes/Flat-Remix-Blue/gnome-shell/gnome-shell-theme.gresource   100       auto mode
  1            /usr/share/gnome-shell/gnome-shell-theme.gresource                          10        manual mode
  2            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource               15        manual mode
* 3            /usr/share/themes/Flat-Remix-Blue/gnome-shell/gnome-shell-theme.gresource   100       manual mode

Press <enter> to keep the current choice[*], or type selection number: `

I still don't get the theme when locking/suspending the screen. It's only appearing on first login and when I click on switch users on unlock screen.

**Comment by daniruiz** [comment]
Sorry but I'm completely unable to replicate this issue. I've tested it several times with different ubuntu versions and they all work :(
My only advice is to try it with a clean install, or completely uninstalling the theme and installing it back from source
