### ISSUE TITLE
Gnome 3.36.4 Abnormal icon size

### ISSUE THREAD

**Issue by danieldeng2** [daniruiz/flat-remix-gnome#163]
when dash to dock is placed at the bottom of the screen, it changes the grid icon size so that the icons are too small:

![Screenshot from 2020-08-20 04-00-33](https://user-images.githubusercontent.com/36489683/90753481-93dc8880-e2d0-11ea-9cb6-509671c8f81d.png)

The screenshots are taken on a surface pro 7 with scale set to 200%

**Comment by daniruiz** [comment]
Sorry but that's the normal behaviour of the shell. That is not caused by my theme

**Comment by danieldeng2** [comment]
> Sorry but that's the normal behaviour of the shell. That is not caused by my theme

Is there anyway I could fix this by changing the css?

**Comment by daniruiz** [comment]
No, sorry
