### ISSUE TITLE
gnome-shell icons vertically stretched

### ISSUE THREAD

**Issue by dluigirafael** [daniruiz/flat-remix-gnome#164]
Manjaro
gnome-shell 3.36.6
using latest AUR pkg (latest update caused this issue)
![Screenshot from 2020-09-26 13-56-26](https://user-images.githubusercontent.com/37952719/94339192-ad27d180-0000-11eb-8f1d-03fa35ceb59c.png)
![Screenshot from 2020-09-26 13-56-40](https://user-images.githubusercontent.com/37952719/94339193-adc06800-0000-11eb-9aba-d5e9f55c3ace.png)

**Comment by daniruiz** [comment]
Hi! thanks for reporting.
I've noticed that issue but only after installing the theme. When you logout & login the issue is gone. Can you confirm this?

**Comment by daniruiz** [comment]
Akay, I've found the issue. Working on it right now ;)

**Comment by daniruiz** [comment]
Fixed!
Thanks for reporting!
