### ISSUE TITLE
Small theme inconsistency..?

### ISSUE THREAD

**Issue by sylqvq** [daniruiz/flat-remix-gnome#166]
Hey! First off, I just want to say thank you for this amazing theme; ever since I added it to my system's themes I have never switched back. There was one small problem that has been pushing me to kind of wanting to, though. When I use this theme, the battery icon on the bar doesn't seem themed at all, which kind of throws off the system's feel a bit, you know?

(Screenshot)
![Screenshot from 2020-10-20 15-21-15](https://user-images.githubusercontent.com/57052622/96640342-a2531a80-12e8-11eb-8f1a-8658aa0e02a2.png)

Is there a system setting that I haven't set, or is this the theme? (and if it is the theme, may I request that the battery's icons are added?)

Thank you!

**Comment by KushagraKarira** [comment]
I'm also using the same theme on gnome 3.38 on Debian testing with all 3 flat-remix themes
but there seems to be no problem on my system.

are you running some top-bar extension ?

Cropped screenshot attached
![Screenshot from 2020-10-21 22-28-07](https://user-images.githubusercontent.com/36698785/96753239-2ee70100-13ed-11eb-84fd-1496a81878e9.png)

**Comment by sylqvq** [comment]
I'm using Dash to Panel; but even if I disable it, the battery icon still remains "blocky.."

![image](https://user-images.githubusercontent.com/57052622/97019137-90a28a80-1515-11eb-8fab-07ca93e2e51d.png)

Is there anything different that you did? Any theme I apply the icon is like this..

**Comment by sylqvq** [comment]
If it is any help, these are the extensions that I am using.

![image](https://user-images.githubusercontent.com/57052622/97019745-4ff74100-1516-11eb-8e85-38777e666103.png)

**Comment by daniruiz** [comment]
This might be an issue with the icon theme, as the shell theme can't control the icons, so try completely removing the icon theme and then reinstalling it again

**Comment by sylqvq** [comment]
Yup, it was actually my shell, I'm so sorry I didn't get back to this sooner. Apparently, just installing a "Pop Shell Icon" extension (or something similar, I cannot remember) fixed it completely for me. Very sorry for that.
