### ISSUE TITLE
Error when i am scrolling apps list

### ISSUE THREAD

**Issue by vuminhcongvmc** [daniruiz/flat-remix-gnome#167]
[error-gnome-shell-theme.zip](https://github.com/daniruiz/flat-remix-gnome/files/5417983/error-gnome-shell-theme.zip)

Please fix it, I think this error from max with of apps list (My English is very bad). Thank you.

**Comment by daniruiz** [comment]
Hi! Sorry but that's not an issue of the theme, maybe it's caused by gnome itself or an extension that you've installed
