### ISSUE TITLE
Login Screen Not Changed Fedora 33

### ISSUE THREAD

**Issue by Prn-Ice** [daniruiz/flat-remix-gnome#169]
I installed the theme by using
```
sudo dnf copr enable daniruiz/flat-remix
sudo dnf install flat-remix-gnome
```

After installing and selecting one of the themes via the gnome tweak tool, the shell gets changed but when I restart or lock the screen I see no difference.
Lovely theme by the way.

**Comment by daniruiz** [comment]
Just tested it on fedora 33 and it's working perfectly
![image](https://user-images.githubusercontent.com/12565871/109274860-43605d80-7814-11eb-8127-c92f408ed9ad.png)

Try completely removing it and reinstall it. Or maybe install it from this repo instead of copr
