### ISSUE TITLE
Dark shell theme doesn't work.

### ISSUE THREAD

**Issue by MauricioGlz** [daniruiz/flat-remix-gnome#172]
I have downloaded the latest version of the theme from the ubuntu repository, and the dark variant of any color is not working at all, it sets the accent color right but the shell still looks white.

**Comment by hellowluan** [comment]
For change _shell theme_ do you need using an **extension** of **gnome-extensios**.
Here is a tutorial teaching how to activate Full Dark Mode 
[How to Enable Full Dark Mode on Ubuntu 20.04](https://www.omgubuntu.co.uk/2020/04/enable-full-dark-mode-in-ubuntu-20-04)
