### ISSUE TITLE
Only installing a single version (for login screen)

### ISSUE THREAD

**Issue by AJJLagerweij** [daniruiz/flat-remix-gnome#173]
Thanks for the nice theme, the only issues I have are related to the login screen.
I'm working on ubuntu 20.04 and try to install a specific version for the login screen.
Following the steps that you indicate:
```bash
git clone https://github.com/daniruiz/flat-remix-gnome
cd flat-remix-gnome
make && sudo make install
```
result in:
1. The default blue login screen.
2. It installs all themes
How can I install, for example, only the Red Darkest fullPanel themes, and make it have the gresource file necessary for the login screen?

**Comment by daniruiz** [comment]
Then instead of installing all the themes, copy the Flat-Remix-Red-Darkest-fullPanel directory inside `~/.themes` or `/usr/share/themes`

**Comment by AJJLagerweij** [comment]
Sorry, I'm still kinda stumped. Your explanation indeed helped me to install only specific shell themes. However, I'm still not managing to make that specific theme accessible by the login screen.

I can still only see the blue theme as an option for gdm3. How do I get one of the other versions to show up here?
```bash
pc@pc:~$ update-alternatives --config gdm3-theme.gresource   
Er zijn 3 beschikbare keuzemogelijkheden voor het alternatief gdm3-theme.gresource (dat voorziet in /usr/share/gnome-shell/gdm3-theme.gresource).

  Keuze        Pad                                                                        Prioriteit Status
------------------------------------------------------------
* 0            /usr/share/themes/Flat-Remix-Blue/gnome-shell/gnome-shell-theme.gresource   100       automatische modus
  1            /usr/share/gnome-shell/gnome-shell-theme.gresource                          10        handmatige modus
  2            /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource               15        handmatige modus
  3            /usr/share/themes/Flat-Remix-Blue/gnome-shell/gnome-shell-theme.gresource   100       handmatige modus

Druk <enter> om de huidige keuze[*] te behouden, of typ een keuzenummer in: 
```
