### ISSUE TITLE
Nautilus windows get resized 

### ISSUE THREAD

**Issue by japkov** [daniruiz/flat-remix-gnome#174]
Each time I'm closing Nautilus windows on Manjaro GNOME (3.38) these get resized down by 2 pixels on height - it doesn't matter which variant of theme is in use but it happens to flat-remix only. Also, so far no other application behaves in such way - Thunar works fine, so does for example gnome-system-monitor.

[Video](https://streamable.com/4wx9zn)

I know it's a really weird issue but irks me

**Comment by daniruiz** [comment]
Duplicated https://github.com/daniruiz/flat-remix-gtk/issues/72
