### ISSUE TITLE
Flat remix theme influences on other shell themes

### ISSUE THREAD

**Issue by fastovst** [daniruiz/flat-remix-gnome#175]
Hello,
If I change the shell theme to another one (Yaru-dark, Pop-dark, Orchis etc), the shell status bar looks weird, as if the Flat-remix's artifacts are still in place. Platform: Arch linux with Gnome 3.38.4.

![Screenshot from 2021-02-21 17-48-35](https://user-images.githubusercontent.com/14261148/108630372-2a9b2500-746d-11eb-98cf-cec1e0786074.png)
This is the screenshot with Yaru-dark selected as shell theme. 

Restarting shell or re-logging in does not help.

**Comment by daniruiz** [comment]
If you install the login theme, then the default theme gets overwritten. Shell themes inherit the styles from the default gnome theme, so when you replace it, then all themes inherit from the new theme.
If you want to use another theme you need to uninstall the login theme

**Comment by PrzemekSkw** [comment]
@daniruiz How to uninstall that theme?
