### ISSUE TITLE
Flat-remix change my panel permanently

### ISSUE THREAD

**Issue by PrzemekSkw** [daniruiz/flat-remix-gnome#176]
Hello,
I install full set with `make` and `sudo make install`. Now I cannot bring back my panel to default look.

![Zrzut ekranu z 2021-03-31 10-28-54](https://user-images.githubusercontent.com/25219988/113132789-35d93180-921f-11eb-8327-a6477d9f4b70.png)

How to fix this?
Regards.

**Comment by csteinforth** [comment]
You could try `sudo make uninstall`, or as a last resort reinstall the `gnome-shell` package.

**Comment by PrzemekSkw** [comment]
Thanks, 'sudo make uninstall' help.
Regards.
