### ISSUE TITLE
Red GDM theme

### ISSUE THREAD

**Issue by maydayv7** [daniruiz/flat-remix-gnome#177]
After installing the `flat-remix-gnome` package from the Fedora COPR repo, the GDM theme changes to a light theme with blue accent. Is there any way it can be changed to the same style as flat-remix-red-dark? Also, where is the `gresource` file for the current GDM theme?

(By the way, I'm really loving this theme. Thanks a lot!)

**Comment by daniruiz** [comment]
As a workarround you can change the base theme name in the Makefile
https://github.com/daniruiz/flat-remix-gnome/blob/master/src/gresource/Makefile#L2

and then run again `make && sudo make install` in the root directory of the project

**Comment by daniruiz** [comment]
I've made the selected user in gdm login grey, instead of the default blue. As making it customizable would be a nightmare, sorry.
At least it doens't look bad now with other colored backgrounds, so hope that helps enough
