### ISSUE TITLE
Update flat-remix-gnome for Fedora 34 in COPR

### ISSUE THREAD

**Issue by maydayv7** [daniruiz/flat-remix-gnome#178]
As flat-remix has recently added support for GNOME 40, can you please update the `flat-remix-gnome` package in the COPR repo for Fedora 34, especially as there are many users already using the pre-release, and the official release is in about 20 days.

**Comment by TheCultLeader666** [comment]
would really appreciate this

**Comment by daniruiz** [comment]
Fixed! Sorry for the delay ;)

**Comment by maydayv7** [comment]
Thanks a lot!! :+1:
