### ISSUE TITLE
Strange text shadow on panel and search bar

### ISSUE THREAD

**Issue by TheCultLeader666** [daniruiz/flat-remix-gnome#180]
Upon installing this theme, I encountered a problem with the text on both the panel and the search bar (screenshots below)
![Screenshot from 2021-04-27 08-48-47](https://user-images.githubusercontent.com/65368815/116244445-ed396900-a735-11eb-9a55-6bebda06667b.png)
![Screenshot from 2021-04-27 08-49-29](https://user-images.githubusercontent.com/65368815/116244468-f32f4a00-a735-11eb-8ffa-8df64129b3d7.png)

**Comment by daniruiz** [comment]
Yes, for some reason text-shadows are not working great with  gnome 40 :(

**Comment by TheCultLeader666** [comment]
> Yes, for some reason text-shadows are not working great with gnome 40 :(

Maybe you could make a version that doesn't have text-shadows? I myself don't see a need for them.

**Comment by daniruiz** [comment]
I've finally opened a bug report for gnome https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4409

**Comment by GlenMerlin** [comment]
Would the text and icon shadow issues also be affecting the folders? as those appear to be broken on gnome 40.3

**Comment by daniruiz** [comment]
Folders are working fine in gnome 40. What do you mean?
Could you provide a screenshot?

**Comment by GlenMerlin** [comment]
It appears to be an issue with this theme where the shading on the folders looks really blocky and awkward

granted this is manjaro and they just updated to gnome40 and there are all kinds of really strange issues (see the squished at the top)
![image](https://user-images.githubusercontent.com/43477600/125661886-d5736e00-8412-4799-9f12-5e62d0104aa1.png)

switching to other themes seems to fix the issue

![image](https://user-images.githubusercontent.com/43477600/125662472-61f61919-5177-4489-8dce-4d59edd73f65.png)

and I just downloaded and reinstalled the theme from gnome-look yesterday

**Comment by daniruiz** [comment]
All icon and text shadows got fixed in GNOME 40.3 so this can be fixed now.

Unfortunately this new version breaks box-shadows for some other elements :sweat_smile: 
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4477

@GlenMerlin just pushed an update that fixes all this issues. Thanks for reporting, when you wrote it I still had not tested GNOME 40.3

**Comment by GlenMerlin** [comment]
thank you so much!
