### ISSUE TITLE
Weird shadow outline?

### ISSUE THREAD

**Issue by Vixtron** [daniruiz/flat-remix-gnome#182]
I noticed that this is probably fine in the theme screenshots, but I think the outline looks weird.
![image](https://user-images.githubusercontent.com/22355590/120800501-5041cb00-c540-11eb-90f3-04e91635518c.png)
![image](https://user-images.githubusercontent.com/22355590/120800602-6bacd600-c540-11eb-80fd-5582ef36dbd9.png)

**Comment by 13k** [comment]
I agree, it looks weird, specially having dealt with compositor visual artifacts for years, where these huge borders were very common and the first sign that something was wrong.

For panels I think it's ok-ish, but for dropdown menus it instantly brings up PTSD feelings.

**Comment by daniruiz** [comment]
I quite like it. I added it to be able to have a shadow under the popup, as gnome-shell has a bug that cuts the shadows otherwise.
That way you can see the popup if it's over a white background
![image](https://user-images.githubusercontent.com/12565871/123006090-79bf7b00-d3b7-11eb-889b-2e28cc758ff9.png)

**Comment by Vixtron** [comment]
> I quite like it. I added it to be able to have a shadow under the popup, as gnome-shell has a bug that cuts the shadows otherwise.
> That way you can see the popup if it's over a white background
> ![image](https://user-images.githubusercontent.com/12565871/123006090-79bf7b00-d3b7-11eb-889b-2e28cc758ff9.png)

Could there at least be a version without these outlines with regular shadows?

**Comment by daniruiz** [comment]
Sorry but I can't create new variants for every request I get. That'd be crazy. :laughing: 
For now the theme will remain the same. Maybe if shadows get fixed in gnome-shell I'll revert this change and use regular shadows instead
