### ISSUE TITLE
The font on the toolbar is a little bit small

### ISSUE THREAD

**Issue by rdgh8** [daniruiz/flat-remix-gnome#183]
I'm on 3.38 for reference. [Here](https://user-images.githubusercontent.com/66289396/122696226-a1281380-d210-11eb-993b-511ff78f2c90.mp4) is how it looks compared to other shell themes installed on my system. I just feel that the font could be a little bigger? Also, for some reason the Gnome search bar turns white when you start typing on it, would it be possible to keep it black?

**Comment by daniruiz** [comment]
Sorry but that's a design choice I like and I can't make everyone happy :(

**Comment by rdgh8** [comment]
Sorry, do you know where I can edit this font myself?
