### ISSUE TITLE
[Suggestion] Animate when the cursor hovers over an icon

### ISSUE THREAD

**Issue by rdgh8** [daniruiz/flat-remix-gnome#184]
Some other themes will animate when the cursor hovers above an icon, ex. the date menu, so that the background changes color a bit which makes it easier to see. 

https://user-images.githubusercontent.com/66289396/124342822-d891ab00-db94-11eb-9390-a3f1a5624dff.mp4

Also, I'm not sure if its a bug or issue on my end, but the "pressed" animation for this theme looks a bit strange, as you can see in the video, it's like a white half circle that appears under the icon that you click? Would it be possible to have that changed so that it would just change the background color like when hovering over it with a cursor, but just do it in a different color?

**Comment by daniruiz** [comment]
That is fixed now with the theme for GNOME 40 :wink:
