### ISSUE TITLE
Folder background in gnome 40 blocky

### ISSUE THREAD

**Issue by aditya-shri** [daniruiz/flat-remix-gnome#188]
I think it's not rendering correctly as the background of folders in the drawer appearing blocky.

**Comment by daniruiz** [comment]
Could you provide a screenshot.
Also try the latest theme uploaded here, as I think you are having issues due to the update to GNOME  40.3, which is now fixed

**Comment by aditya-shri** [comment]
> Could you provide a screenshot.
![shadow](https://user-images.githubusercontent.com/18643014/126488638-6a586fe9-c1bf-43bc-a305-aed472f11c6d.png)

**Comment by daniruiz** [comment]
Si, that's fixed now
![image](https://user-images.githubusercontent.com/12565871/126498894-da4f37e5-f998-4666-83fe-0bf5ad8cde7c.png)


You new to download the latest theme from this repo
