### ISSUE TITLE
Only available in 'Shell' in gnome-tweaks

### ISSUE THREAD

**Issue by telometto** [daniruiz/flat-remix-gnome#189]
I have extracted the archives and tried copying them into both `.themes` and `/usr/share/themes` but the only thing I can choose is in the 'Shell' subcategory inside `gnome-tweaks` - the 'Applications' subcategory shows all other themes.

**Comment by telometto** [comment]
I am using Fedora 34 and I found your themes inside the official repos, but they do not seem to be up-to-date and compatible with GNOME 40. Are there going to be any fixes down the line or are they abandoned? Love the themes, btw!
![flat-remix](https://user-images.githubusercontent.com/65364211/132087270-99d28419-d17a-48d8-8a59-65beb4c45c10.png)

**Comment by TheCultLeader666** [comment]
This is the wrong repo. You're looking for flat-remix-gtk

**Comment by telometto** [comment]
> This is the wrong repo. You're looking for flat-remix-gtk

Thanks, I'll see over there.
