### ISSUE TITLE
Window title bar issues.

### ISSUE THREAD

**Issue by mlebjerg** [daniruiz/flat-remix-gnome#190]
Hi there i recently installed your login theme, but afterwards i had some problems in some programs like VSCode and Webull wont render correctly. The window title bar doesn't show up in these programs any more. Here are some screenshots:
![image](https://user-images.githubusercontent.com/32514341/137143399-68902af0-80db-41b0-8c00-244931bfdfbd.png)

![image](https://user-images.githubusercontent.com/32514341/137143337-6fecbf32-8e2b-4f74-b5d3-f102f27b039a.png)

I have already tried reverting back to all the original pop theme. Uninstalling your theme, and reinstalling gnome-shell, Reinstalling gnome and pop-desktop, pop-shell, all the GTK packages and i cannot get it to work again.

I am writing this issue in hope that you can help me get this working because i am completely lost.

**Comment by TheCultLeader666** [comment]
This is most likely an app problem not a theme problem. Have you tried enabling native windows for these apps?
