### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by telometto** [daniruiz/flat-remix-gnome#191]
I'm using Fedora 34 and I checked the version of the theme in the repos and they are all outdated ([here](https://pkgs.org/search/?q=gnome-shell-theme-flat-remix) and [here](https://pkgs.org/search/?q=flat-remix-theme)); your [Copr](https://copr.fedorainfracloud.org/coprs/daniruiz/flat-remix/builds/) has failed, and the instructions [here](https://drasite.com/flat-remix-gnome) do not seem to work on Fedora 34, either.

Big fan of your work, so I just thought I'd give you a heads up.

**EDIT:** the [gnome-look.org](https://www.gnome-look.org/p/1013030) does not work, either. The only thing that is possible to enable is the shell theme.

**Comment by daniruiz** [comment]
This is now fixed with Fedora 35
