### ISSUE TITLE
Some toggles are improperly colored 

### ISSUE THREAD

**Issue by rdgh8** [daniruiz/flat-remix-gnome#194]
Some toggles are improperly colored when using the flat remix theme. I'm using Pop!_OS 21.10 beta, and the newest version of the theme from Gnome Look for Gnome 40 + 41. You can see from the image that when the toggles are in the "off" position, the background is white. 

![image](https://user-images.githubusercontent.com/66289396/143670196-8e0d4693-5871-4c29-9ae0-00622a6e6943.png)

**Comment by daniruiz** [comment]
They are properly colored. They are more contrasted than the switches in the gtk theme
