### ISSUE TITLE
Visual artifacts on Gnome 41.2

### ISSUE THREAD

**Issue by JekRock** [daniruiz/flat-remix-gnome#195]
Hi and thank you for the cool theme!

I've just installed the theme running
```bash
sudo dnf install gnome-shell-theme-flat-remix
```
and it seems like there are some visual artifacts on Gnome 41.2 when using any theme.
I have `Blur my shell` installed, but it was disabled when I was making the screenshots.

`Dash to dock` displays rounded corners incorrectly
![image](https://user-images.githubusercontent.com/5882133/145808166-6330d307-1a29-4f91-9eef-4fe65dac1c1e.png)
Some windows have white lines at the top
![image](https://user-images.githubusercontent.com/5882133/145808394-9baf8cc4-181b-4810-bc87-f3f6b6cdb070.png)
On the search screen, there are artifacts on the search results' corners
![image](https://user-images.githubusercontent.com/5882133/145808653-26bd1fbb-8877-4c4e-a1bd-1081e4f9b779.png)
It seems like the menu also has some issues with shadows and corners (not sure here, but it looks different from the screenshots with examples)
![image](https://user-images.githubusercontent.com/5882133/145808890-f9ed8fd5-3b38-499d-a224-65498e5f182a.png)
![image](https://user-images.githubusercontent.com/5882133/145811008-c6140f80-382d-4b08-a9d9-f8ac4d0915c1.png)

Let me know if you need any details.

**Comment by ruathudo** [comment]
Same on mine. It happens with the App Folder too.

**Comment by daniruiz** [comment]
That's not the updated theme for gnome 41. That's the theme I made for gnome 40, you need to update it

**Comment by JekRock** [comment]
@daniruiz it was installed via `dnf`. What way of installing the theme do you recommend?

**Comment by ruathudo** [comment]
@daniruiz  I think the Fedora DNF repo hasn't been updated. The package is from 2020.

**Comment by daniruiz** [comment]
I'll ping the maintainer of the repository and try to update the official fedora package.
For now you can use my copr repo, where I upload all the latest releases
https://copr.fedorainfracloud.org/coprs/daniruiz/flat-remix/packages/


```sh
sudo dnf copr enable daniruiz/flat-remix
sudo dnf install flat-remix-gnome
```

**Comment by JekRock** [comment]
@daniruiz thanks!

**Comment by daniruiz** [comment]
Hello @tim77
I can remember you helped packaging the official flat-remix packages for fedora. Could you help us updating the packages flat-remix-gtk and flat-remix-gnome? I've seen that you recently updated the icon theme to the latest release :tada: 
Thank you in advance :wink:

**Comment by tim77** [comment]
Hello everyone. Update submitted in Fedora and available for testing. Please test it:

- https://bodhi.fedoraproject.org/updates/FEDORA-2021-31aaa5cce3
- https://bodhi.fedoraproject.org/updates/FEDORA-2021-80918a5574
- https://bodhi.fedoraproject.org/updates/FEDORA-2021-8f6f53175f

_I am still would like if one day we could build it properly from sources and install GDM theme properly..._

**Comment by daniruiz** [comment]
Thank you @tim77!
About the GDM theme, I'd love that too, but GDM doesn't actually support themes which makes it hard to package without braking anything. My package does it by replacing a core file of GDM, so if you install the wrong version gdm will crash.

So I think it's better on COPR and have only the gnome themes on the official repos
