### ISSUE TITLE
[Question] - How can I change my overview background image?

### ISSUE THREAD

**Issue by Dvlnst** [daniruiz/flat-remix-gnome#196]
Hi,

I saw in your demo images a different overview background image. I've reinstalled the theme, but it doesn't change at all.

Kind regards.

**Comment by daniruiz** [comment]
You need to download the theme and build it yourself. That way it will use your current background
```
git clone https://github.com/daniruiz/flat-remix-gnome
cd flat-remix-gnome
make && sudo make install
```

**Comment by Dvlnst** [comment]
I do build it myself, that's why I'm asking if I was missing something.

Output:
> /home/USER/.local/share/backgrounds/2021-10-18-15-07-51-Wallpaper.jpg
> if [ ! -z "/home/USER/.local/share/backgrounds/2021-10-18-15-07-51-Wallpaper.jpg" ] && [ ".jpg" != ".xml" ] ; \
> then \
> 	if [ 6 -le 1 ] ;\
> 	then \
> 		cp -f "/home/USER/.local/share/backgrounds/2021-10-18-15-07-51-Wallpaper.jpg" src/gresource/login-background ;\
> 	else \
> 		convert -scale 10% -gaussian-blur 0x6 -resize 1000% "/home/USER/.local/share/backgrounds/2021-10-18-15-07-51-Wallpaper.jpg" src/gresource/login-background ;\
> 	fi; \
> fi
> make -C src/gresource build
> make[1]: Entering directory '/home/USER/.public-projects/Flat-Remix-Gnome-Themes/src/gresource'
> cp ../../themes/Flat-Remix-Blue-Light/gnome-shell/gnome-shell.css gnome-shell.css
> cp ../../themes/Flat-Remix-Blue-Dark/gnome-shell/gnome-shell.css gnome-shell-dark.css
> cp ../../themes/Flat-Remix-Blue-Dark-fullPanel/gnome-shell/gnome-shell.css gnome-shell-high-contrast.css
> 'gnome-shell-high-contrast-dark.css' -> 'gnome-shell-high-contrast.css'
> cp ../sass/gnome-shell/upstream/pad-osd.css .
> sed "s/assets/resource:\/\/\/org\/gnome\/shell\/theme/g" -i *.css
> glib-compile-resources gnome-shell-theme.gresource.xml
> make[1]: Leaving directory '/home/USER/.public-projects/Flat-Remix-Gnome-Themes/src/gresource'
> mkdir -p /usr/share/themes/
> cp -a themes/Flat-Remix-Black-Light themes/Flat-Remix-Black-Light-fullPanel themes/Flat-Remix-Blue-Dark themes/Flat-Remix-Blue-Darkest themes/Flat-Remix-Blue-Darkest-fullPanel themes/Flat-Remix-Blue-Dark-fullPanel themes/Flat-Remix-Blue-Light themes/Flat-Remix-Blue-Light-fullPanel themes/Flat-Remix-Brown-Dark themes/Flat-Remix-Brown-Darkest themes/Flat-Remix-Brown-Darkest-fullPanel themes/Flat-Remix-Brown-Dark-fullPanel themes/Flat-Remix-Brown-Light themes/Flat-Remix-Brown-Light-fullPanel themes/Flat-Remix-Cyan-Dark themes/Flat-Remix-Cyan-Darkest themes/Flat-Remix-Cyan-Darkest-fullPanel themes/Flat-Remix-Cyan-Dark-fullPanel themes/Flat-Remix-Cyan-Light themes/Flat-Remix-Cyan-Light-fullPanel themes/Flat-Remix-Green-Dark themes/Flat-Remix-Green-Darkest themes/Flat-Remix-Green-Darkest-fullPanel themes/Flat-Remix-Green-Dark-fullPanel themes/Flat-Remix-Green-Light themes/Flat-Remix-Green-Light-fullPanel themes/Flat-Remix-Grey-Dark themes/Flat-Remix-Grey-Darkest themes/Flat-Remix-Grey-Darkest-fullPanel themes/Flat-Remix-Grey-Dark-fullPanel themes/Flat-Remix-Grey-Light themes/Flat-Remix-Grey-Light-fullPanel themes/Flat-Remix-Magenta-Dark themes/Flat-Remix-Magenta-Darkest themes/Flat-Remix-Magenta-Darkest-fullPanel themes/Flat-Remix-Magenta-Dark-fullPanel themes/Flat-Remix-Magenta-Light themes/Flat-Remix-Magenta-Light-fullPanel themes/Flat-Remix-Miami themes/Flat-Remix-Miami-Dark themes/Flat-Remix-Miami-Dark-fullPanel themes/Flat-Remix-Miami-fullPanel themes/Flat-Remix-Orange-Dark themes/Flat-Remix-Orange-Darkest themes/Flat-Remix-Orange-Darkest-fullPanel themes/Flat-Remix-Orange-Dark-fullPanel themes/Flat-Remix-Orange-Light themes/Flat-Remix-Orange-Light-fullPanel themes/Flat-Remix-Red-Dark themes/Flat-Remix-Red-Darkest themes/Flat-Remix-Red-Darkest-fullPanel themes/Flat-Remix-Red-Dark-fullPanel themes/Flat-Remix-Red-Light themes/Flat-Remix-Red-Light-fullPanel themes/Flat-Remix-Teal-Dark themes/Flat-Remix-Teal-Darkest themes/Flat-Remix-Teal-Darkest-fullPanel themes/Flat-Remix-Teal-Dark-fullPanel themes/Flat-Remix-Teal-Light themes/Flat-Remix-Teal-Light-fullPanel themes/Flat-Remix-Violet-Dark themes/Flat-Remix-Violet-Darkest themes/Flat-Remix-Violet-Darkest-fullPanel themes/Flat-Remix-Violet-Dark-fullPanel themes/Flat-Remix-Violet-Light themes/Flat-Remix-Violet-Light-fullPanel themes/Flat-Remix-White-Dark themes/Flat-Remix-White-Darkest themes/Flat-Remix-White-Darkest-fullPanel themes/Flat-Remix-White-Dark-fullPanel themes/Flat-Remix-Yellow-Dark themes/Flat-Remix-Yellow-Darkest themes/Flat-Remix-Yellow-Darkest-fullPanel themes/Flat-Remix-Yellow-Dark-fullPanel themes/Flat-Remix-Yellow-Light themes/Flat-Remix-Yellow-Light-fullPanel /usr/share/themes
> cp -r share/ /usr/
> glib-compile-schemas /usr/share/glib-2.0/schemas/
> mkdir -p /usr/share/gnome-shell/theme/
> '/usr/share/gnome-shell/theme/Flat-Remix-Blue-Light' -> '/usr/share/themes/Flat-Remix-Blue-Light/gnome-shell/'
> cp src/gresource/gnome-shell-theme.gresource /usr/share/themes/Flat-Remix-Blue-Light/gnome-shell/gnome-shell-theme.gresource
> update-alternatives --install /usr/share/gnome-shell/gdm-theme.gresource gdm-theme.gresource /usr/share/themes/Flat-Remix-Blue-Light/gnome-shell/gnome-shell-theme.gresource 100

Result:
![Screenshot from 2021-12-18 13-13-38](https://user-images.githubusercontent.com/36289254/146640585-4fb0a7d4-afff-490c-be3d-f125c5f6f31b.png)

**Comment by daniruiz** [comment]
ooooh sorry, I didn't read you meant the overview background. Thought it was the login one as I get too many opened issues for that.
It's an extension https://extensions.gnome.org/extension/3193/blur-my-shell/

**Comment by Dvlnst** [comment]
Thank you! I thought I was something relate with your theme. I appreciate your work very much.

Kind regards.
