### ISSUE TITLE
support for Ubuntu LTS Jammy

### ISSUE THREAD

**Issue by maxadamo** [daniruiz/flat-remix-gnome#198]
do you mind adding support for the coming ubuntu release? 
I want to upgrade ASAP but I could not survive without flat-remix :smile_cat:

**Comment by daniruiz** [comment]
Will do it soon ;)

**Comment by daniruiz** [comment]
Uploaded!

**Comment by maxadamo** [comment]
@daniruiz while this is working. the themes "Darker" vanished with the latest upgrade, and I liked them because despite the name, they weren't too dark.
