### ISSUE TITLE
GNOME 42  popup items are dark in light theme

### ISSUE THREAD

**Issue by daitj** [daniruiz/flat-remix-gnome#199]
In the top bar, the items that are in popup menu are dark in light theme `Flat-Remix-Blue-Light-fullPanel`

![Screenshot from 2022-04-05 14-49-38](https://user-images.githubusercontent.com/682274/161748239-b3886d3a-4077-48f3-b85d-b07b019f5fea.png)

**Comment by daniruiz** [comment]
As a workarround for now, you can download the themes I develop for Kali Linux, which do support GNOME 42 right now

Download it and you will find the themes under usr/share/themes, copy kali-dark and kali-light. 

https://gitlab.com/kalilinux/packages/kali-themes/-/tree/c242cd89184024b31296c47a4d2fa962ad98b735/share/themes

**Comment by daitj** [comment]
kali-light also has same issue. Could it be issue with gnome itself?

**Comment by daniruiz** [comment]
I've uploaded all the themes for GNOME 42 ;)
