### ISSUE TITLE
Strange OSD after update

### ISSUE THREAD

**Issue by xVANKO** [daniruiz/flat-remix-gnome#200]
Hi, after update, I have strange "new looking" OSD.
Volume bar is outside of the gray box. Is this correct?

![Screenshot from 2022-04-15 16-38-31](https://user-images.githubusercontent.com/62944093/163584135-65782c43-d420-4f23-ae09-2c9402029bbc.png)

**Comment by daniruiz** [comment]
You are using the theme for GNOME 42 in a previous version of gnome.
You need to download the theme for your shell version. Run gnome-shell --version to check it
