### ISSUE TITLE
Add support for Gnome 42

### ISSUE THREAD

**Issue by fsevenm** [daniruiz/flat-remix-gnome#202]
I just updated to Ubuntu 22.04 which uses Gnome 42.1. The background and the font colour on gnome shell seem broken.
 
![image](https://user-images.githubusercontent.com/29963765/167172942-71427ef7-6a09-499f-bec8-b6ca082486b6.png)

**Comment by daniruiz** [comment]
The theme already supports gnome 42

**Comment by fsevenm** [comment]
You got any clue what makes the background white?

**Comment by daniruiz** [comment]
that you installed the theme for gnome 3.38

**Comment by fsevenm** [comment]
Oh right, that's true. My `/home/user/.themes` didn't sync with the `/usr/share/themes`. Now works! Thanks.
