### ISSUE TITLE
Top panel broken in Fedora 36

### ISSUE THREAD

**Issue by JuanLuVermejo** [daniruiz/flat-remix-gnome#203]
Hi, i always use the Flat-Remix-Blue-Darkest wich one had the top bar with some spaces on the corners, but after install fedora 36 it seems to be broken and don't fit in the original space for the top bar. 

This is my journalctl -r report after load the theme. Only the fullpanel option works fine.

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561507b246d0] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561507b20740] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561505b8a350] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x56150661b240] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x561505be4a00] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5615063f31a0] is on because it needs an allocation.`

`may 14 12:07:59 juanlulap gnome-shell[3938]: loading user theme: /usr/share/themes/Flat-Remix-Blue-Darkest-fullPanel/gnome-shell/gnome-shell.css`

`may 14 12:07:55 juanlulap gnome-shell[3938]: loading user theme: /usr/share/themes/Flat-Remix-Blue-Dark/gnome-shell/gnome-shell.css`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561507b246d0] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561507b20740] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561505b8a350] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x56150661b240] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x561505be4a00] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: Can't update stage views actor <panelBox>[<StBoxLayout>:0x5615063f31a0] is on because it needs an allocation.`

`may 14 12:07:50 juanlulap gnome-shell[3938]: loading user theme: /usr/share/themes/Flat-Remix-Blue-Darkest/gnome-shell/gnome-shell.css`

**Comment by daniruiz** [comment]
could you share a screenshot?

**Comment by JuanLuVermejo** [comment]
Yes,
This is how the top bar look currently
![toppanelerror2](https://user-images.githubusercontent.com/20727776/168445651-328e50dc-b1a9-4b90-96dc-ca7d52c80538.png

This is my journalctl
![toppanelerror](https://user-images.githubusercontent.com/20727776/168445650-4ba2a8f3-c3e4-479c-a962-fbadfc8f80ea.png)

**Comment by JuanLuVermejo** [comment]
Yes,
This is how the top bar look currently
![toppanelerror2](https://user-images.githubusercontent.com/20727776/168445725-da1a4427-a1c1-4e61-9241-b67f5275f7a5.png)


This is my journalctl
![toppanelerror](https://user-images.githubusercontent.com/20727776/168445730-6cadf368-b08e-48f3-bdc4-f2bf547b7243.png)

**Comment by daniruiz** [comment]
You are using a the top panel blur extension. If you want to use blurred panel use the fullPanel theme version

**Comment by JuanLuVermejo** [comment]
Ok, thank you @daniruiz! Now works
