### ISSUE TITLE
Doesn't work on Gnome 42.1

### ISSUE THREAD

**Issue by reagentoo** [daniruiz/flat-remix-gnome#204]
Can't get themes to work. I used various instructions: installation to `/usr/share/themes/` and `/home/user/.themes`. Don't see it in gnome-tweaks.
What exactly should be in the directories? I guess:
```
/usr/share/themes/Flat-Remix-*/gnome-shell/assets/*.svg
/usr/share/themes/Flat-Remix-*/gnome-shell/gnome-shell.css
```
It's enough?

Config:
gnome-shell-42.1
gnome-tweaks-42.beta (tried gnome-tweaks-40.0 also)

**Comment by daniruiz** [comment]
Can you show what you have inside the themes folder?
Also, do you have the gnome-shell themes extension installed?

https://extensions.gnome.org/extension/19/user-themes/

**Comment by reagentoo** [comment]
> Can you show what you have inside the themes folder?
```
$ ls -1 .themes
Flat-Remix-Brown-Dark
Flat-Remix-Brown-Darkest
Flat-Remix-Brown-Darkest-fullPanel
Flat-Remix-Brown-Dark-fullPanel
Flat-Remix-Brown-Light
Flat-Remix-Brown-Light-fullPanel
```

> Also, do you have the gnome-shell themes extension installed?
```
*  gnome-extra/gnome-shell-extensions
      Latest version available: 42.1
      Latest version installed: 42.1
```

**Comment by daniruiz** [comment]
And gnome-tweaks does let you pick a theme for the shell?

**Comment by reagentoo** [comment]
> And gnome-tweaks does let you pick a theme for the shell?

no

**Comment by daniruiz** [comment]
Then you have the user themes extension installed but not enabled. Check it in gnome-extensions app

**Comment by reagentoo** [comment]
> Then you have the user themes extension installed but not enabled. Check it in gnome-extensions app

Thanks! I've enabled "User Themes" in the extension list.
I change the appearance of the panel (dash-to-panel), but the appearance of the windows does not change.

**Comment by daniruiz** [comment]
the window themes are another thing. You need the gtk theme https://github.com/daniruiz/Flat-Remix-GTK
