### ISSUE TITLE
I'm using Flat Remix on Wayland. How can I set the backgrounds of Multitasking View and Show Applications?

### ISSUE THREAD

**Issue by Yukai-Qian** [daniruiz/flat-remix-gnome#205]
I noticed in the Multitasking view of the demo images that the background is set to a blurred wallpaper:
![GNOME-40](https://user-images.githubusercontent.com/100383998/171421029-f3c04dc2-6cca-4d06-aa45-343fab5ca64e.png)

I'm wondering how I can get this effect on Wayland, if possible. Currently, the backgrounds of Multitasking View and Show Applications are both grey.
![image](https://user-images.githubusercontent.com/100383998/171423023-2ed1199b-47a6-47fc-b598-9eb37be617ce.png)

Thanks in advance.

**Comment by simurgh9** [comment]
I believe this maybe the blur my shell Gnome extension.

**Comment by Yukai-Qian** [comment]
Thanks! Worth noting: to prevent Blur My Shell from creating undesired dark rectangles around the top bar and the dock, we need to set its Brightness to 1.00 in the GNOME Extension Manager.

![Screenshot from 2022-06-05 09-18-00](https://user-images.githubusercontent.com/100383998/172052974-ff168645-23db-4577-a362-e3663e8742e6.png)
