### ISSUE TITLE
Panel icons look very bad up in small high-DPI displays

### ISSUE THREAD

**Issue by firinael** [daniruiz/flat-remix-gnome#210]
![image](https://user-images.githubusercontent.com/67032657/187776001-d2ccbbf4-1378-45e0-b052-bcfd532b847c.png)
![image](https://user-images.githubusercontent.com/67032657/187776513-b4906d9e-6130-49db-bb99-05cf047db124.png)

As you can see, the stroke width is too thin for smaller, high-DPI displays. They lose readability, simply put. Is it possible to change just the icons, or have some optional filled icons?

Thanks!

**Comment by daniruiz** [comment]
Sorry but that's an issue with gnome-shell and it's caused by the icon-theme. There's nothing I can do from this theme code
