### ISSUE TITLE
The expand arrow for panel icons not aligned properly

### ISSUE THREAD

**Issue by AToMiXhawK** [daniruiz/flat-remix-gnome#217]
The expand arrow for panel icons like Network, Bluetooth, Power mode are not aligned properly.

Please refer to the attached screenshots

![Screenshot from 2023-04-21 12-46-49](https://user-images.githubusercontent.com/42279685/233569756-d9284223-d671-4568-8761-b74583265ffe.png)
![Screenshot from 2023-04-21 12-47-13](https://user-images.githubusercontent.com/42279685/233569781-2b607650-2969-4dc1-aabf-bab90779c88f.png)

**Comment by seVenVo1d** [comment]
Same problem

**Comment by AToMiXhawK** [comment]
Started seeing this after upgrade to Fedora 38 with Gnome 44.0

Image 1: Gnome 43.4 (Fedora Silverblue 37)
![gnome_43 4_fedora_silverblue_37](https://user-images.githubusercontent.com/42279685/233850580-fd660f48-815c-4a0b-aec7-9e8b2cd3fcde.png)

Image 2: Gnome 44.0 (Fedora Silverblue 38)
![gnome_44 0_fedora_silverblue_38](https://user-images.githubusercontent.com/42279685/233850639-56254f17-5f00-4ce4-a21a-a474af4898d1.png)

**Comment by daniruiz** [comment]
You need to use the branch in gnome-44 https://github.com/daniruiz/flat-remix-gnome/tree/gnome-44
