### ISSUE TITLE
Oversized Quick Setting icons

### ISSUE THREAD

**Issue by Chrispycode** [daniruiz/flat-remix-gnome#219]
I'm on Manjaro 22.1 GNOME 43.5
![Screenshot from 2023-05-08 22-18-14](https://user-images.githubusercontent.com/22537998/236925851-84f25983-8882-43e8-a3f1-0d7314e06721.png)

**Comment by daniruiz** [comment]
You need to use the theme for gnome 43 https://github.com/daniruiz/flat-remix-gnome/releases/tag/20221107

**Comment by Chrispycode** [comment]
Sorry I'm stupid
