### ISSUE TITLE
The top bar has greater height than it should have.

### ISSUE THREAD

**Issue by D4VID0x2** [daniruiz/flat-remix-gnome#220]
The top bar has greater height and covers part of the title bar of windows that are maximized.  
Red line denotes where it should end.

![image](https://github.com/daniruiz/flat-remix-gnome/assets/47712832/5bc4863f-b990-4c4b-a5a3-129c685a8fb0)

Archlinux, GNOME 44.1  
aur/flat-remix-gnome 20230508-1 fullPanel

**Comment by daniruiz** [comment]
I'm closing this as it's based on an old version of the theme. If the issue persists please feel free to open a new report
