### ISSUE TITLE
[Dark Theme] Text inside Dialog Box not clearly visible

### ISSUE THREAD

**Issue by abhiroop43** [daniruiz/flat-remix-gnome#221]
Text inside Dialog Boxes not clearly visible.

This is for the Darkest Full Panel theme for Gnome 3.38.

Screenshot below for reference.

![image](https://github.com/daniruiz/flat-remix-gnome/assets/5673129/fbe9049a-08ec-4b77-99de-425994ead959)

**Comment by daniruiz** [comment]
That's clearly not my theme, sorry
