### ISSUE TITLE
gnome 43 bug wth quick settings

### ISSUE THREAD

**Issue by dragonek93** [daniruiz/flat-remix-gnome#222]
theme has upgraded to gnome 44 but what if i still in use gnome 43? Debian still has 43 version. Quick settings bars are bold for gnome 44 and not compatible with gnome 43. Where can i download flat-remix-gnome for gnome 43 version? i see other branches are not on github

**Comment by stigman9393** [comment]
> How to remove it correctly through the terminal?

what you want to remove?

**Comment by daniruiz** [comment]
There's a version of the theme for each gnome-shell version. Make sure you check https://drasite.com/flat-remix-gnome
