### ISSUE TITLE
Problem with top bar on Fedora 38/Gnome 44

### ISSUE THREAD

**Issue by saculo** [daniruiz/flat-remix-gnome#223]
Hi,
I've got weird issue with every Gnome Shell it looks like that at the end: 
![image](https://github.com/daniruiz/flat-remix-gnome/assets/37440952/6ee9583a-880c-4c7c-b9a2-18fd8168ebeb)
Do you have any idea why does it look like that?

Thanks.

**Comment by daniruiz** [comment]
That issue is caused by blur gnome-shell extension. I recommend using the fullPanel version if the blur setting is applied to the top-bar
