### ISSUE TITLE
Color-Scheme not applied to password prompts

### ISSUE THREAD

**Issue by John2324** [daniruiz/flat-remix-gnome#228]
I installed the flat-remix-magenta-dark on my system for full icons, shell,  and gdm login. The color scheme is consistent for the most part, except for prompts that require a root password.

I'm using Debain 12 with gnome shell version 43.9 and I noticed a blue (assuming default color) ring on certain window prompts that require a root password. 
 
![Screenshot from 2024-04-26 18-08-24](https://github.com/daniruiz/flat-remix-gnome/assets/54280648/c2f6ae0d-8fbf-459b-b76a-59bd18864fb5)

Is there any modification I have to do to the `makefile` in order to remove that blue-color highlight?

**Comment by daniruiz** [comment]
This is now fixed
