### ISSUE TITLE
Text colour of notification in Flat-Remix-*-Light themes are unreadable. 

### ISSUE THREAD

**Issue by xraynaud** [daniruiz/flat-remix-gnome#229]
Hello, 

I am using the Flat-Remix-Gray-Light-Fullpanel theme and the notification text is unreadable (it seems to be white on light gray, with a greenish shadow). The text becomes readable on hover. 

I tried to find where this colour scheme is in the gnome-shell.css without success. 

notification: 
![Capture d’écran du 2024-07-01 15-51-44](https://github.com/daniruiz/flat-remix-gnome/assets/7243861/c1faf83c-e411-4dec-b924-cc0610d15304)

notification after hover:
![Capture d’écran du 2024-07-01 15-52-27](https://github.com/daniruiz/flat-remix-gnome/assets/7243861/06b6e469-8886-4d91-a2d0-69ee44d1c69b)

This behaviour seems to happen with all Flat Remix Light themes.

**Comment by daniruiz** [comment]
Are you sure you are using the correct theme version for you gnome-shell release?
check `gnome-shell --version` command

**Comment by daniruiz** [comment]
I'm unable to reproduce this issue. Make sure you install the correct version of the theme for you shell version
https://drasite.com/flat-remix-gnome
