### ISSUE TITLE
Buttons not themed correctly on GNOME 46

### ISSUE THREAD

**Issue by siddhpant** [daniruiz/flat-remix-gnome#230]
![image](https://github.com/user-attachments/assets/dfec78b0-4390-4b31-b1cd-b5dea8df2d5d)

Even though I have Orange theme set:

![image](https://github.com/user-attachments/assets/ad63d95c-edeb-4cce-ab1e-5d80cea09fae)

(Also note the window buttons being stretched.)

**Comment by Mistakesos** [comment]
Taking green one as an example. We have a file in `~/.themes/Flat-Remix-GTK-Green-Dark/install.sh`   run it by command `./install`

Or move that's files by yourself, using `cp ~/.themes/Flat-Remix-GTK-Green-Dark/gtk-4.0/* ~/.config/gtk-4.0`. Then relogin, or reboot. Themes will works.

Hope this will help you.

**Comment by siddhpant** [comment]
@Mistakesos the issue is something else. It's not about installation.

**Comment by daniruiz** [comment]
Sorry but this repository is for the gnome-shell theme

**Comment by siddhpant** [comment]
Oops sorry, opening in gtk repo
