### ISSUE TITLE
The green theme is broken in the latest version and appears blue

### ISSUE THREAD

**Issue by Mistakesos** [daniruiz/flat-remix-gnome#231]
![截图 2024-09-23 03-25-40](https://github.com/user-attachments/assets/3dbe669d-d39c-4b0e-933e-46b0a1c01067)
![截图 2024-09-23 03-25-49](https://github.com/user-attachments/assets/9f34fa8e-1e47-425d-a56b-3ba2b96d51fc)
![截图 2024-09-23 03-26-46](https://github.com/user-attachments/assets/863d4f26-16ae-4775-9336-a6e0c214a8a2)

Just install "Flat-Remix-Green-Dark" on gnome-look by ocs-url. Then using gnome-tweaks change shell theme. Now we have wrong color.

Shell version: 47.0
Theme version: 20240922
System: Arch Linux rolling

**Comment by Mistakesos** [comment]
![截图 2024-09-23 15-22-54](https://github.com/user-attachments/assets/9065f95f-2e79-44d7-9cc1-5becc14ed8e2)



I try to use 20240813, at least it's works,

**Comment by Sidethorn** [comment]
Go to change wallpaper section and from there, you see the coloured  dots under the light/dark selector,  change the accent colors of the shell. At least that's a temporary fix for gnome shell 47.

**Comment by Mistakesos** [comment]
> Go to change wallpaper section and from there, you see the coloured dots under the light/dark selector, change the accent colors of the shell. At least that's a temporary fix for gnome shell 47.

![image](https://github.com/user-attachments/assets/0d485582-eda7-4665-93ab-70a0ceed7ea5)
But the color is still not the same as the theme color downloaded, which is a solution that is not beautiful. Or install the 20240813 series version (old version) on gnome-look. I also found that the "Theme color options" in the location you mentioned are all displaying errors due to Flat-Remix-GTK-Green-Dark or Flat-Remix-Green-Dark (shell theme). Now it looks like it's mixed with my background, but when I put the cursor over it, there is still a description and I can select and change the color. (There are more details in the image) 
Anyway, thank you for your reply and I am happy for you willingness to help!  :)

**Comment by Sidethorn** [comment]
![image](https://github.com/user-attachments/assets/6082b068-38f1-4bda-b356-61e093100f68)
 Well I'm sorry that for you didn't worked, mine looks fine.

**Comment by Mistakesos** [comment]
> ![image](https://private-user-images.githubusercontent.com/6005852/373949603-6082b068-38f1-4bda-b356-61e093100f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjA4NzIsIm5iZiI6MTcyODIyMDU3MiwicGF0aCI6Ii82MDA1ODUyLzM3Mzk0OTYwMy02MDgyYjA2OC0zOGYxLTRiZGEtYjM1Ni02MWUwOTMxMDBmNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDZUMTMxNjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmVjNTk4OTBhNDFlYmM4ZTExNTg1MjA5YTNhMjViMTM5NTViZGQwMzFjZTA2Y2JkYTEwZGFkZDgzZDU5MjlkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.evdKHOiHQDOgKeqxcZl12KEVBXLK3hL60NWaGONalTE) Well I'm sorry that for you didn't worked, mine looks fine.

I means, the function of change clolor is work, I can click them, but just the button is mixed with background, I mentioned Perhaps it's because I installed Flat-Remix-GTK-Green-Dark(GTK theme) or Flat-Remix-Green-Dark(shell theme) I can't confirm which one it is, because even if I restore them all to default, it won't help. When I try to set them (shell theme and gtk theme) to default, the button looks all white :( , I still can change colors. I means the buttons is all white, just display error, but function is well🤔.

**Comment by daniruiz** [comment]
Since gnome 47 the color highlighting can't be customized from the theme and has to be set from the Appearance setting.
If you are using GNOME 46 use the previous version https://github.com/daniruiz/flat-remix-gnome/tree/20240813
