### ISSUE TITLE
[Gnome 47]

### ISSUE THREAD

**Issue by enx1998** [daniruiz/flat-remix-gnome#235]
Hi,
with Gnome 47 the close button of the window border of the gtk4 apps is too big and the is not shaped properly compared to gtk3 apps.

gtk4 app
![immagine](https://github.com/user-attachments/assets/9499a172-ca2a-40e7-b2f4-7d94025a3c7f)

gtk3 app
![immagine](https://github.com/user-attachments/assets/b2acba78-642a-439a-826f-74d197fcf0e5)

Thanks ENx

**Comment by daniruiz** [comment]
Sorry but this repository is for the gnome theme
