### ISSUE TITLE
way too unrelated, a question about the kde's flat remix

### ISSUE THREAD

**Issue by DaRandomCube** [daniruiz/flat-remix-gnome#236]
4 years since the last commit in the flat-remix repo
when will it get an update? i'm curious as i'm interested into flat themes

**Comment by daniruiz** [comment]
where do you see 4 years? this repo was updated last week.
The icon theme is not updated so often but last commit was 6 months ago

**Comment by DaRandomCube** [comment]
idk as i looked at this repo
https://github.com/daniruiz/flat-remix-kde

**Comment by DaRandomCube** [comment]
ooooh i only mentioned kde in the issue name, not in the issue content itself
my bad

**Comment by daniruiz** [comment]
oh, sorry, my bad. I didn't read the title.
Unfortunately yes, the flat-remix KDE themes are no longer maintained. I don't use plasma myself and I find it hard to keep them up to date
