### ISSUE TITLE
doesn't seem to work with font scaling

### ISSUE THREAD

**Issue by nergdron** [daniruiz/flat-remix-gnome#30]
I've got my fonts set to 1.3x size in gnome-tweak-tool because I've got a 4k display, and this works in most gtk themes, but the font used in this shell theme don't appear to be respecting this setting, they're still tiny.

**Comment by uuujf** [comment]
+1 here

**Comment by daniruiz** [comment]
The new release supports font scaling factor perfectly. PPA repository isn't still updated but you can download it from here.
