### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by modzilla99** [daniruiz/flat-remix-gnome#34]
Would U mind telling me where I can find these wallpapers, mate?

**Comment by daniruiz** [comment]
All the wallpapers are taken from wallhaven.cc:

https://alpha.wallhaven.cc/wallpaper/370718
https://alpha.wallhaven.cc/wallpaper/294634
https://alpha.wallhaven.cc/wallpaper/298018
https://alpha.wallhaven.cc/wallpaper/605991
