### ISSUE TITLE
Gradient in top panel

### ISSUE THREAD

**Issue by rayfun** [daniruiz/flat-remix-gnome#38]
Hi,

after installing your Flat Remix Gnome Shell theme and applying it, the top panel has a color gradient which is quite awful and I do not see it in any of your screenshots.
What's going on here? How can I fix/change this?

Best regards,
Ray

![screenshot from 2018-05-06 12-16-06](https://user-images.githubusercontent.com/15213735/39672269-53eda8ae-5127-11e8-8b91-8efc4e9a735e.png)

**Comment by davidaik** [comment]
Happens on Ubuntu 18.04 as well, but only when a window is maximized. If there are no maximized windows, the panel is flat translucent. Really undesirable when the whole point of the theme is to be flat.

**Comment by davidaik** [comment]
This is fixed in my pull request. You can do it on your device by adding a CSS property in your installed theme. Find these lines
```
#panel {
  text-shadow: 0 0 4px rgba(0, 0, 0, 0.5);
  border-radius: 5px;
  font-weight: normal;
  font-size: 12px;
  height: 24px;
  color: white;
  background: rgba(0, 0, 0, 0.2); }
```

Update it to

```
#panel {
  text-shadow: 0 0 4px rgba(0, 0, 0, 0.5);
  border-radius: 5px;
  font-weight: normal;
  font-size: 12px;
  height: 24px;
  color: white;
  background: rgba(0, 0, 0, 0.2);
  background-gradient-direction: none; }
```

**Comment by daniruiz** [comment]
Thanks!

I though it was something just ubuntu had hard coded and could only be disabled by resetting gnome-shell to vanilla version.
I've just pulled your solution.
