### ISSUE TITLE
VSCode and Sublime Text show Strange open Dialog (GTK2 Artifacts?) 

### ISSUE THREAD

**Issue by raveesh-me** [daniruiz/flat-remix-gnome#41]
Here is the issue:
![Open dialog in VSCode](https://user-images.githubusercontent.com/15698263/40569721-9ab1621a-60a1-11e8-8d1a-cde6ff1016f8.png)
![screenshot from 2018-05-26 04-55-36](https://user-images.githubusercontent.com/15698263/40569771-f98d4aec-60a1-11e8-87f2-7cbd27a3743c.png)

Themes:
Application: Flat-Remix-GTK-Dark
Cursor: Communitheme
Icons: Flat-Remix-Dark
Shell: Flat-Remix-dark-Miami

OS:
Ubuntu 18.04

Gnome Version: 3.28.1

**Comment by daniruiz** [comment]
Wow ... That's really weird. As you can see here, It doesn't happen to me, :
! [image] (https://user-images.githubusercontent.com/12565871/40570837-52bc222c-608f-11e8-815d-e85c0f466264.png)

This issue should be in https://github.com/daniruiz/flat-remix-gtk anyway, as it is GTK theming related.

Have you tried installing the last Flat Remix GTK theme?

**Comment by raveesh-me** [comment]
> This issue should be in https://github.com/daniruiz/flat-remix-gtk anyway, as it is GTK theming related.

My bad, I'm closing this issue here and referencing this issue in the relevant repo.

**Comment by raveesh-me** [comment]
> Have you tried installing the last Flat Remix GTK theme?

I just installed using the ppa
