### ISSUE TITLE
Is it possible to make the top bar larger?

### ISSUE THREAD

**Issue by vladoxNCL** [daniruiz/flat-remix-gnome#42]
Hi dani,

Just tried out your theme and it looks gorgeous! However, due to my poor eyesight I find the top bar fonts to be a little bit too small, and they wont become larger even if I modify the system fonts or change the font size on the css file of your theme. Could you please point me to how can I modify the css to make text bigger?

Thanks a lot, and congratulations on your lovely theme again!

**Comment by daniruiz** [comment]
I can't make the topbar bigger as many people would complain about it taking to much space, but last updates brought great font scaling support. So I think this issue can be considered as solved now.
