### ISSUE TITLE
Dark theme doesn't match the colour scheme of flat-remix-gtk-dark

### ISSUE THREAD

**Issue by kovaacs** [daniruiz/flat-remix-gnome#43]
I love the flat-remix theme, and I don't understand why the dark themes use different colours. Do you plan to match them in the future? Right now the GTK theme uses #383C4A, but this gnome theme uses black as base colour, etc.

**Comment by daniruiz** [comment]
Yes! I plan to match both colors the problem is that every change I've tried looks weird and when similar colors are applied and, for example, you open gnome shell notifications tab, the windows and the panel can't be distinguished.

**Comment by daniruiz** [comment]
New Flat Remix GTK dark theme has been redesigned and now it is really black:
![image](https://user-images.githubusercontent.com/12565871/46954344-9b0d2c80-d090-11e8-99e4-72a40ec68454.png)
