### ISSUE TITLE
Cant change the theme (Install via Terminal Ubuntu 18.04)

### ISSUE THREAD

**Issue by AlexisThink** [daniruiz/flat-remix-gnome#44]
I tried to change to the different variations of this theme. But i dont have the .themes folder.
And ifter i install, not show options or any other dialog.

How can i do that?

**Comment by JJPeterson** [comment]
First make sure you have Gnome Tweaks and Gnome Shell extensions installed: 

`sudo apt install gnome-tweaks gnome-shell-extensions`

Then once you've got those installed you need to log out of your session and log back in. NOTE: If you have auto login turned on a restart will not work, you need to log off. 

Once your logged back in open up Gnome Tweaks and go to `Extensions`. You'll likely notice way more options then you had before. Enable `User themes`. Exit and reopen Tweaks for it to take effect.

Now under Appearance you should have new options.
