### ISSUE TITLE
Compact version with Gnome 3.30

### ISSUE THREAD

**Issue by xzj8b3** [daniruiz/flat-remix-gnome#47]
But make it a compact version with Gnome 3.30 for small monitors

With reduced-size calendar and user menus and optimized menus!!!

Nice as theme but too big menu!!!

**Comment by daniruiz** [comment]
As you may know, I can't provide personalized themes with different sizes for each taste. Many people are asking for larger or smaller variants but I think they can easily solve it by changing font-scaling from gnome-tweaks.
