### ISSUE TITLE
gnome tweak tool can't recognize theme in fedora 28

### ISSUE THREAD

**Issue by Himanshu40** [daniruiz/flat-remix-gnome#50]
Today I just installed in my fedora 28 gnome version 3.28 but gnome tweak tool is unable to recognize it.
Any way to get it back ?
btw I had used these comands:-
```
sudo dnf copr enable daniruiz/flat-remix
sudo dnf install flat-remix-gnome
```

**Comment by daniruiz** [comment]
Do you have user-themes extension installed and activated?
