### ISSUE TITLE
Bug on panel when use Blyr

### ISSUE THREAD

**Issue by btd1337** [daniruiz/flat-remix-gnome#53]
This bug occurs when Blyr extension is enable.

![captura de tela de 2018-11-04 05-18-10](https://user-images.githubusercontent.com/11943860/47961398-53bfef00-dff1-11e8-9a73-1cd5ed95a6bf.png)

**Comment by daniruiz** [comment]
I've added variants without panel padding so that they work fine with Blyr extension
