### ISSUE TITLE
Sound and brightness sliders in pop-up are invisible

### ISSUE THREAD

**Issue by f-marelli** [daniruiz/flat-remix-gnome#55]
When tuning the sound volume or the screen brightness using hotkeys, the slider in the pop-up is invisible.
The sliders below the icons should show the status of the tuned parameter, but it is completely gray as shown on the screenshots below.

![screenshot from 2018-11-13 12-29-20](https://user-images.githubusercontent.com/10929150/48410737-d195a000-e73f-11e8-9f84-f86a7ba8ea73.png)
![screenshot from 2018-11-13 12-29-01](https://user-images.githubusercontent.com/10929150/48410746-d6f2ea80-e73f-11e8-8940-78ebeafd1bb9.png)

**Comment by daniruiz** [comment]
Try latest version and tell me if it is fixed

**Comment by f-marelli** [comment]
It is fixed, thanks.
