### ISSUE TITLE
Top bar clock is not ticking

### ISSUE THREAD

**Issue by WojciechCichy** [daniruiz/flat-remix-gnome#56]
The clock placed on the Gnome's top bar is not ticking every second as it is with standard Gnome theme.
Instead it jumps every 2-3 seconds.

**Comment by daniruiz** [comment]
What? LMAO! so random.... :rofl: 
Anyway that's not my theme's issue, I touched nothing about the seconds. It may be an issue from gnome-shell's theme engine.
