### ISSUE TITLE
When I open many pages of terminal or firefox, I can't know how many that I've opened.

### ISSUE THREAD

**Issue by Index-Out-Of-Range** [daniruiz/flat-remix-gnome#59]
I think that you should show the number of app I've opened. Thank you.

**Comment by daniruiz** [comment]
I don't understand what you mean. Can you provide some screenshots?

**Comment by Index-Out-Of-Range** [comment]
When I use another theme, I can see that I've opened two chrome from the
side bar because there are two dots on the left side of the icon.
But when I use flat-remix-gnome I can't know that.
I hope you can modify it successfully so that I can continue to use your
theme.
[image: 1.png]
[image: 2.png]

DяA <notifications@github.com> 于2018年12月26日周三 上午7:21写道：

**Comment by daniruiz** [comment]
I can't see the images, sorry. Can you please send them again?
