### ISSUE TITLE
Not working on Fedora release 29 (Twenty Nine)

### ISSUE THREAD

**Issue by CreatorHelper0** [daniruiz/flat-remix-gnome#60]
Any theme not working

**Comment by daniruiz** [comment]
I'm using Fedora 29 right now and I have no problems. Can you provide me some information about how you installed it?

**Comment by trochdewei** [comment]
@daniruiz Problem is that we cannot change gnome-shell theme after recent flat-remix-gnome update from https://copr.fedorainfracloud.org/daniruiz/flat-remix

$ rpm -qi flat-remix-gnome
Name        : flat-remix-gnome
Version     : 20190111r3
Release     : 1

**Comment by daniruiz** [comment]
Overwriting gnome-shell files is the only way to modify gdm theme, sorry for that :man_facepalming: . If you want to override it just reinstall gnome-shell.
`sudo dnf reinstall gnome-shell`
