### ISSUE TITLE
[Question] How to find out what CSS a element is using

### ISSUE THREAD

**Issue by cslux** [daniruiz/flat-remix-gnome#61]
Hey @daniruiz!

First thank you for those themes,  I really like them, create job!

But I want to change a view buttons theme, but struggle to found out what the CSS name is of those buttons. Is there any good way to found out what CSS a button is using in GNOME.

For instance I want to change the notification button, when it has focus, since there is no difference.

Thank you!

regards,
Christian

**Comment by daniruiz** [comment]
Gnome-shell LookingGlass inspector has an element selector built in.

To use it just type `alt+F2` and insert `lg`. This will open LookingGlass panel, where you can find the element inspector icon at the top-right corner.
Hope this helps you :)
