### ISSUE TITLE
How can I change the login wallpaper?

### ISSUE THREAD

**Issue by Typhlos** [daniruiz/flat-remix-gnome#62]
Hi,

I changed the file login-backgroung.png in the the Flat-Remix-Dark theme directory but it doesn't seem to have any impact on the login wallpaper. I suppose I have to regenerate the gnome-shell-theme.gresource but I don't know how to do that.
I use the Flat Remix Dark theme installed with your copr repository on Fedora 29.
Thank you and sorry if you explained that already and I couldn't find it.

**Comment by n3amil** [comment]
You have to rebuild the gresource thats correct. I just did it for myself:
Within the src folder there is a build.sh script which does everything (you need scss and glib-compile-resources installed). Just replace the login-background.jpg (there are multiple jpgs with this name in each flat remix directory, i simply replaced all of them, i guess within src would be enough) with your own login-background.jpg and run "sh build.sh" afterwards. From the readme:
`cd /tmp && rm -rf flat-remix-gnome &&
git clone https://github.com/daniruiz/flat-remix-gnome && cd flat-remix-gnome 
`
sudo mv /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.old &&
sudo ln /usr/share/themes/Flat-Remix/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource`

**Comment by daniruiz** [comment]
I'm still figuring how to provide an easy way to modify the login background, but for now there is no way but to regenerate `gnome-shell-theme.gresource` as I explain here:

Inside `src/assets` directory you'll find all the images that are attached to gresouce file for each theme variant. The one you want to change in this case is named as `login-background.jpg`.
Once you've modified all the assets you want, open a terminal inside `src` directory. Here you need to execute `./build.sh` but as it needs sass to be installed you can execute the following script instead:
```bash
#!/bin/sh

TMP="/tmp/flat-remix-gnome"

rm -rf "$TMP"
mkdir -p "$TMP"

# Copy CSS files
for theme in ../Flat-Remix*
do
  cp "$theme"/gnome-shell/gnome-shell.css "$TMP/$(basename $theme).css"
done

# Copy assets
for assets in assets/*
do
  target=../"${assets#assets/}"/gnome-shell/assets
  rm -f "$target"/*
  cp -rf "$assets"/* "$target"
done

# Generate gresource files
cp -r assets/* "$TMP"
cp ../Flat-Remix-Darkest/gnome-shell/gnome-shell.css "$TMP"/gnome-shell-high-contrast.css
cat << EOF >> "$TMP"/gnome-shell-high-contrast.css
stage {
  -st-icon-style: symbolic;
}

.toggle-switch-us, .toggle-switch-intl {
  background-image: url("resource:///org/gnome/shell/theme/toggle-off-hc.svg");
}

.toggle-switch-us:checked, .toggle-switch-intl:checked {
  background-image: url("resource:///org/gnome/shell/theme/toggle-on-hc.svg");
}
EOF
sed "s/assets/resource:\/\/\/org\/gnome\/shell\/theme/g" -i "$TMP"/*.css
for theme in "$TMP"/Flat-Remix*/
do
  cp gnome-shell-theme.gresource.xml "$theme"
  cp "$TMP"/"$(basename ${theme%/})".css "$theme"gnome-shell.css
  cp "$TMP"/gnome-shell-high-contrast.css "$theme"
  cp pad-osd.css "$theme"
  (cd "$theme" && glib-compile-resources gnome-shell-theme.gresource.xml)
  cp "$theme"/gnome-shell-theme.gresource ../$(basename "$theme")
done
```

**Comment by Typhlos** [comment]
Thank you for the explanations.
I certainly made a mistake during the process but I can't get it working by using the script you provide here @daniruiz or by installing sass and using the build.sh script. GDM crashes and I just get a black screen. Maybe it's due to the picture I'm trying to use? It's a jpeg file taken with my camera and resized to a 16:9 ratio with Shotwell.

**Comment by Und3rCover96** [comment]
please add this feature to change new login wallpaper all the time like as win10 not only one wallpaper
and add customize lock screen please tnx

**Comment by Kaibura** [comment]
> Maybe it's due to the picture I'm trying to use? It's a jpeg file taken with my camera and resized to a 16:9 ratio with Shotwell.

Yes @Typhlos, in `/flat-remix-gnome/src/sass/gnome-shell-sass/_common.scss` the image for the background is retrieved as `login-background.jpg`

```scss
#lockDialogGroup {
  background: url("assets/login-background.jpg");
  background-size: cover;
}
```
By using **ctrl+F** in `_common.scss` you can search for `login-background.jpg` and change the extension to ".jpeg"
Cheers.

**Comment by jedichen121** [comment]
I'm experiencing the same issue. Even when I change the application theme back to default, the login background (after log out or restart) is still the one used by flat remix. Does it overwrite any system settings that even default theme is affected? I tried to change the file `/etc/alternatives/gdm3.css` without success. Thanks.

**Comment by daniruiz** [comment]
I've finally updated the src/build.sh file so that you can generate your own themes with the login background you want.
Just execute ```./build.sh --login-background FILE``` and all variants will be updated.
Then copy the gnome-shell-theme.gresource file to /usr/share/gnome-shell

**Comment by daniruiz** [comment]
@jedichen121 are you using Ubuntu?

**Comment by Typhlos** [comment]
@daniruiz, thanks a lot, I really appreciate it. I'll try it and give you my feedback.

**Comment by Typhlos** [comment]
Well, I tried it and it failed. The sh script didn't failed or gave me an error but when rebooting, I just got a black screen instead of the login screen and I had to login using a tty to put back the original gresource file. I used these 2 pictures : [this one](https://framapic.org/1Sl4Fu0xC1rG/jUCTerEzLmCR.jpg), but I believed it failed because this pictures has a too high resolution for my screen (4K and my screen has a Full HD resolution), so I tried [this one](https://framapic.org/iIi4TkGrGiQ4/enlYU9BdwcfY.jpg) matching my resolution but again with no success. I really do not understand while it keeps failing. I followed your instruction : 

`cd flat-remix-gnome/src
./build.sh --login-background /path/to/the/wallpaper
sudo make install
sudo mv /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.old
sudo ln /usr/share/themes/Flat-Remix/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource`

If you need any further information from me, just ask.

**Comment by daniruiz** [comment]
I've tried what you executed with the first wallpaper and it worked perfectly for me. No idea what wen't wrong.
Are you using the latest version from github. Try to update it and rerun the script

```bash
cd flat-remix-gnome/src
./build.sh --login-background /path/to/the/wallpaper
cd ..
sudo make install
sudo mv -n /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.old
sudo ln -sf /usr/share/themes/Flat-Remix/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by Typhlos** [comment]
I did a `git pull` just before that. I also use zsh and not bash but I don't think it changes anything since your sh script specify to use sh. And I'm using the Dark version of your Flat Remix. Does the gresource file have to match the version I'm using? I didn't try it, I'll try that an give you an update.

**Comment by daniruiz** [comment]
@Typhlos I'm also using zsh at the moment and as you said it doesn't matter as the script specifies sh shell. And the themes don't need to match.
Which distro are you using by the way? Because if you are using ubuntu things are a bit different :sweat_smile:

**Comment by Typhlos** [comment]
I'm using Fedora 29 with Gnome 3.30.2.

**Comment by daniruiz** [comment]
@Typhlos I'll try now with my laptop with also Fedora 29. Let's see if we find out the problem

**Comment by Typhlos** [comment]
Ok, thank you very much !

**Comment by daniruiz** [comment]
It is also working for me on Fedora 29. At least try to reinstall gnome-shell, maybe some files are missing there.
```bash
sudo dnf reinstall gnome-shell
```

**Comment by daniruiz** [comment]
@Typhlos also try make uninstall before installing the customized one. Maybe there are some wrong symlinks messing it up.

**Comment by framon98** [comment]
Hey dani, Im new using your theme and I love it, but I'm having an issue changing the login background, I'm using ubuntu 18.04 and I read that you said that the process is differente, can you help me here?

**Comment by daniruiz** [comment]
@framon98 I've just updated Makefile to automatize installation over Ubuntu. Now it's done the same way as any other distro:

```bash
# Inside flat-remix-gnome cloned directory
# don't remove the parenthesis
(cd src && ./build.sh --login-background /path/to/image)
sudo make install
```

You need to have `glib-compile-resources` installed. For Ubuntu just run `sudo apt install libglib2.0-dev-bin`.

#### For ubuntu users:
If you investigate a bit you'll see that ./build.sh isn't needed for you :tada::tada:, as Ubuntu's gnome doesn't care about the .gresource file for theming, so you don't need to install glib-compile-resources either. But explaining different ways of installing it for different distros would be too confusing so I just post here the 'standard' way, so that it works for everyone :smiley:
