### ISSUE TITLE
Flat remix overwrote all shell themes

### ISSUE THREAD

**Issue by emilioferreyra** [daniruiz/flat-remix-gnome#63]
Hi @daniruiz 

First of all, let me thank you for this great job. 

After the last update, flat remix shell theme overwrote every single theme I selected so, I can't change even to default theme:

![selection_329](https://user-images.githubusercontent.com/5206135/51440347-93b37b80-1c9c-11e9-8444-a9baa1ab23ee.png)

If I change to other shell themes, it changes the color configuration, but the top bar remains unchanged:

![selection_330](https://user-images.githubusercontent.com/5206135/51440500-3caea600-1c9e-11e9-84b4-8cecf867e910.png)

I tried uninstalling flat remix, but then I was left without UI to log in. I'm using Fedora 29 workstation with Gnome.

Thanks in advance for your help.

**Comment by daniruiz** [comment]
Replacing gnome-shell's .gresource file is the only way of theming GDM, but it also replaces default shell. If you want Flat-Remix just as shell theme you can install it manually to .themes folder or install it from copr repo and then reinstall gnome-shell:

```bash
sudo dnf copr enable daniruiz/flat-remix
sudo dnf install flat-remix-gnome
sudo dnf reinstall gnome-shell
```
