### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by xuyichenmo** [daniruiz/flat-remix-gnome#65]
i had already installed it. but when i try to restart my kali linux 
i get this
![Y1_TX9Y`KODGWAIC)9L%%[A.png](https://i.loli.net/2019/02/06/5c5ae9ae4d86f.png)

**Comment by daniruiz** [comment]
Sorry but I can't see that image. Can you reupload it?

**Comment by hThoreau** [comment]
On the topic of being unable to launch **something**, I'm currently unable to login after having selected `Flat-Remix-Darkest for Wayland` on my login screen. Trying to login then just sends me right back to the login screen. I'm using a Parrot 4.5 with Wayland.

**Comment by daniruiz** [comment]
With that information I can't do much, I have it running over Ubuntu 17.10-18.10, Fedora 29 and Arch all of them over Wayland and Xorg. If you can provide more information I'd be glad to help you
