### ISSUE TITLE
show desktop icon isn't in the corner

### ISSUE THREAD

**Issue by HenriqueLin** [daniruiz/flat-remix-gnome#67]
Hi, I just download ur latest version of theme(full panel), love it, but get trouble about the 'show desktop' icon of 'dash to panel', it's not really in the corner, there is a little space right of it, not sure is theme's problem or not, pls take a look
![2019-02-25 19-43-33](https://user-images.githubusercontent.com/47987376/53363983-b5f08700-3935-11e9-8c86-279059313824.png)

**Comment by daniruiz** [comment]
It is fixed now :)

**Comment by HenriqueLin** [comment]
> It is fixed now :)

thank u :D
