### ISSUE TITLE
No volume/brightness slider bar in latest version

### ISSUE THREAD

**Issue by m-ark22** [daniruiz/flat-remix-gnome#69]
#55 this issue is closed but I have the same problem after latest update

![Desktop screenshot](https://i.imgur.com/rmaSWB5.jpg)

P.S. Thanks to the author for the best gnome theme

**Comment by daniruiz** [comment]
Which gnome-shell version are you using?

**Comment by m-ark22** [comment]
![Gnome shell version](https://i.imgur.com/ScQAnWT.png)

**Comment by daniruiz** [comment]
They changed the way sliders are themed from gnome-shell 3.28 to 3.30, that's why last time this issue appeared but it was supposed to be fixed. Maybe I reverted the changes without noticing.
As soon as I have some free time I'll fix it.

**Comment by daniruiz** [comment]
I think it's solved with latest update. Please test it and tell me if it really works :)
