### ISSUE TITLE
top bar opacity?

### ISSUE THREAD

**Issue by Miyazono1** [daniruiz/flat-remix-gnome#70]
i know this is not necessarily an issue, but it's something that i think should be addressed, if it isn't already a thing and i'm blind. i'm using the dark full panel version, but i assume this is the same in every version. the top bar is almost completely transparent, which means if you have a window open, you can still see the top bit of your wallpaper, which is not an issue if your wallpaper is all black on the top, but most of mine are not. if there isn't already, there should be a setting that sets the top bar opacity if there is a maximized window.

**Comment by BogdanDarius** [comment]
@Miyazono1 You can do this by yourself. Just go into gnome-shell/gnome-shell.css file search for `#panel {` and then at `background: rgba(56, 60, 74, 0.3);` you can change the opacity from 0.3 to something else.
