### ISSUE TITLE
Not working in Linux mint 19.1

### ISSUE THREAD

**Issue by funcubes** [daniruiz/flat-remix-gnome#72]
I have installed the theme using ppa. It is not showing up in the themes.

**Comment by daniruiz** [comment]
I imagine that if you are using Linux mint you won't have Gnome desktop installed (could be but it would be strange) for which this theme is intended for. I could imagine then that what you're really looking for  are the icon theme or the GTK theme that I also provide here:
github.com/daniruiz/flat-remix
github.com/daniruiz/flat-remix-gtk

**Comment by funcubes** [comment]
My bad. I didn't think too much when I read the "Ubuntu based...".
