### ISSUE TITLE
Login Screen Wallpaper Removed After Updates

### ISSUE THREAD

**Issue by javery86** [daniruiz/flat-remix-gnome#73]
After running the latest updates (via dnf) in Fedora 29, the login screen wallpaper that came with the theme has been removed and replaced with the stock wallpaper that ships with Fedora. Please advise.

**Comment by daniruiz** [comment]
Try to make a clean install:
```bash
sudo dnf remove flat-remix-gnome
sudo dnf reinstall gnome-shell
sudo dnf install flat-remix-gnome
```
Restart the computer and tell me if it works. At the moment I've tested it on my laptop with fedora and it worked fine, but I made some mistakes while creating the package that later I fixed, so maybe you were unlucky and updated with the broken ones.
