### ISSUE TITLE
Could we please have a (more) "solid" version of the theme?

### ISSUE THREAD

**Issue by FreddieChopin** [daniruiz/flat-remix-gnome#74]
I've just installed "flat remix" suite and I like it very much! However there's an issue with the shell theme. If you use vanilla GNOME then there's not problem at all, but if you use extensions like "hide top bar" and/or "dash to dock", then 100% transparent shell theme is not very usable if something is below it. A good image is worth a thousand words, so here are two images (;

top bar with "hide top bar"
![Screenshot from 2019-03-25 20-01-18](https://user-images.githubusercontent.com/1139038/54946857-4f14bc80-4f39-11e9-8e3e-551bccdf3154.png)

dash with "dash to dock", placed at the bottom of the screen
![Screenshot from 2019-03-25 20-02-00](https://user-images.githubusercontent.com/1139038/54946861-51771680-4f39-11e9-9ad4-bbfd50b7c632.png)

I think that for these cases the shell theme should be at most as transparent as the default "flat remix" GTK window theme - possibly a little more solid. Or 100% solid. Or both versions (; Tell me where could I change it manually and I'll tell you what works best in my opinion (;

Related - for these cases where "hide top bar" is used, the top bar could also be bigger (#42), as there is no wasted space when you don't see it (;

Thanks in advance!

**Comment by daniruiz** [comment]
If I remove the theme's transparency it would lose all it's identity, and as I said in the closed issue you mentioned, if I make the panel bigger many people would complain about how much usable space it takes. It's really so hard to please everybody :cry: 

But you can modify it by yourself and I'll be pleased to help you :smile: 
Inside the theme you'll find the gnome-shell.css file with all the styles. What you are looking for is the `#panel` selector (near line 700) where you can modify it's height and opacity. For example

```
#panel {
  font-feature-settings: "tnum";
  text-shadow: 0px 1px 2px rgba(0, 0, 0, 0.9);
  border-radius: 0;
  font-weight: normal;
  font-size: .9em;
  height: 3em; /* for a higher panel */
  color: #ffffff;
  background: black; /* or rgba(0,0,0,.4) where the last number is the opacity */
}
```
