### ISSUE TITLE
The power icon to shut down or restart does not scale as other icons in the quick settings panel.

### ISSUE THREAD

**Issue by rhythm1705** [daniruiz/flat-remix-gnome#76]
The icon is smaller than the other icons in the same row.

**Comment by jshamg** [comment]
Hi daniruiz,
honestly i love your theme. everything is perfect and i love the way i can just install it with dnf in fedora. AWESOME!!! I noticed his bug listed here, too. Just made a screenshot for you. The bug happens because one of the buttons is preselected.

Greetings from Germany,
keep it up!
Josh

![Screenshot from 2019-04-16 18-54-44](https://user-images.githubusercontent.com/32615911/56229241-bbd33080-6079-11e9-97ee-1b24f6d98f54.png)

**Comment by daniruiz** [comment]
I think what he actually means is that the icon shown in the shut-down/restart dialog doesn't vary it's size when font scaling is changed. If so, I can't fix it as this icon's size is hardcoded, it's a gnome-shell's inconsistency

**Comment by rhythm1705** [comment]
No, I mean the icon that is needed to be clicked to get to the screenshot mentioned in the above comment. All other icons such as restart, settings, rotation are properly scaled but the power icon is smaller than others.

**Comment by jshamg** [comment]
Oh hmm, seems that i have misunderstood the problem @rhythm1705 had... But mine could be fixed i think right? @daniruiz .
Greetings from Germany!

**Comment by daniruiz** [comment]
@jshamg Yep, just added to my TODO list for gnome :raised_hands:

**Comment by Weikoi** [comment]
How can this login screen be activated in pop!os ? there is no options for login screen in gnome tweaks.

**Comment by daniruiz** [comment]
@Weikoi  Clone the repo and run `make && sudo make install` then reboot. Be careful as this replaces some important files as the login theme isn't just a theme.

**Comment by Weikoi** [comment]
> @Weikoi Clone the repo and run `make && sudo make install` then reboot. Be careful as this replaces some important files as the login theme isn't just a theme.
Thanks for reply! I have tried this method but it didn't work. The new login interface just flash past and  then get into the original login page. I think maybe it was overwritten by the system.

**Comment by Weikoi** [comment]
@daniruiz Thanks for reply! I have tried this method but it didn't work. The new login interface just flash past and then get into the original login page. I think maybe it was overwritten by the system.

**Comment by daniruiz** [comment]
Then run `make uninstall` and tell me if your login screen works again with default theme.
If you want and login is working again try running only `sudo make install` without the first `make`

**Comment by Weikoi** [comment]
@daniruiz The uninstallation was successful, but the new installation method still does not work. 
/(ㄒoㄒ)/~~

**Comment by daniruiz** [comment]
@Weikoi I forgot to mention you need imagemagick and glib-compile-resources installed `sudo apt install libglib2.0-dev-bin imagemagick`.
Download the latest commit and test it. I've just installed it in Pop OS and worked fine

**Comment by Weikoi** [comment]
@daniruiz it worked！thanks for your patience！and this  theme is very cool, thanks for your work！

**Comment by daniruiz** [comment]
@Weikoi no problem :ok_hand:  Now it's better explained and I've ensured login theming works fine for all distros
