### ISSUE TITLE
User icon too big

### ISSUE THREAD

**Issue by HamburgerJungeJr** [daniruiz/flat-remix-gnome#79]
Hi,

I'm using the flat-remix gnome theme with the flat-remix icons on Ubuntu 19.04 with Gnome 3.32.
I noticed that the user icon where I can logout  is too big
![Issue](https://user-images.githubusercontent.com/11501266/56604763-09641600-6603-11e9-8cee-08caf60c6c82.png)

is there a way to shrink the icon?

**Comment by daniruiz** [comment]
Did you install it from the ppa, because it was outdated and wasn't made for GNOME 3.32. Anyway, I've just updated it, so it should just work fine now.

**Comment by HamburgerJungeJr** [comment]
Yes, I installed the theme from the ppa.

Thanks for the update. The icon is fixed.

What do you recommend to keep the theme up to date?

**Comment by daniruiz** [comment]
The ppa updates automatically with all the other software updates. This time I forgot to update it before Ubuntu 19.04 release :sweat_smile:  but the ppa is usually up to date
