### ISSUE TITLE
adding round corner to dash to panel

### ISSUE THREAD

**Issue by vipertrig** [daniruiz/flat-remix-gnome#80]
Hi, is there any chance you can bring back the round corner dash to panel. Thank you!

**Comment by daniruiz** [comment]
I've been doing some tests but I wasn't able to bring it back just with code. I've found this workaround from Dash to Panel settings that works but it not the best solution:
![image](https://user-images.githubusercontent.com/12565871/57015030-f1981d80-6c12-11e9-9e24-b37846696591.png)

Anyway I opened this issue https://github.com/home-sweet-gnome/dash-to-panel/issues/633 so maybe you want to give it some support. Hope this feature comes back as dash to panel with my theme's panel was my favorite look for gnome :disappointed:

**Comment by daniruiz** [comment]
Just fixed by  @charlesg99 :+1:
