### ISSUE TITLE
White bar on shutdown prompt under cancel button on ubuntu 19.04

### ISSUE THREAD

**Issue by mrayhanhakim** [daniruiz/flat-remix-gnome#82]
Here's the screenshot of the issue:
![Screenshot from 2019-05-04 16-43-35](https://user-images.githubusercontent.com/42672058/57177194-06cbb100-6e8c-11e9-8647-c38ca4d3089a.png)

**Comment by daniruiz** [comment]
That's the selection marker, you can move it with keyboard arrows to select the button with your keyboard. Not my favorite design but does the job... :sweat_smile:
