### ISSUE TITLE
Broken box shadow under workspace switch indicator

### ISSUE THREAD

**Issue by mrayhanhakim** [daniruiz/flat-remix-gnome#83]
Here's the screenshot of the issue (I'm running ubuntu 19.04):
![Screenshot from 2019-05-04 16-41-05](https://user-images.githubusercontent.com/42672058/57177250-a721d580-6e8c-11e9-8b89-6084fbd84d2c.png)

**Comment by daniruiz** [comment]
Do you have other themes installed?

**Comment by mrayhanhakim** [comment]
yes, I have one other theme installed currently

**Comment by daniruiz** [comment]
Wow you are giving me a lot of information... :sweat_smile:
