### ISSUE TITLE
Please revert the shadow commit

### ISSUE THREAD

**Issue by josh1dev** [daniruiz/flat-remix-gnome#84]
Hi!

Would you please be able to revert the changes on the transparent shadow outline? I don't really like it and it looks pretty weird... I really would prefer without, and I think more people do; it doesn't really look that good.

Thanks.

**Comment by daniruiz** [comment]
Well, this change was made because popup menu shadows are broken since gnome-shell 3.28. I really like how it looks :cry:

**Comment by daniruiz** [comment]
I've opened a poll on twitter https://twitter.com/dani_ruiz24/status/1128664343577595904

**Comment by josh1dev** [comment]
Hmm, I feel like it looks better on a white background/shadow. Maybe it's just me idk, but I'm not really a fan of how it looks on the Miami themes. It doesn't really have that nice of a glow on purple I feel like.
