### ISSUE TITLE
Move GDM theme to another package ?

### ISSUE THREAD

**Issue by G-Ray** [daniruiz/flat-remix-gnome#85]
OS: fedora 30, but this should also apply to other Linux distributions 

Currently, the `flat-remix-gnome` package changes the gdm theme.

What about letting the user the choice to install the gdm theme with another package, like `flat-remix-gdm` ?

**Comment by daniruiz** [comment]
Because the gdm theme and the gnome-shell theme are the same. The gdm theme replaces all gnome-shell theme.
