### ISSUE TITLE
Login screen is broken again with flat-remix-gnome 20190526-2

### ISSUE THREAD

**Issue by jeffryang24** [daniruiz/flat-remix-gnome#86]
Dear, author. Thanks for your amazing theme. Currently, I found issue with broken login screen again with following specification:

- Ubuntu 18.04 LTS amd64
- flat-remix/bionic,now 20190525 amd64 [installed]
- flat-remix-gnome/bionic,now 20190526-2 amd64 [installed]
- flat-remix-gtk/bionic,now 20190526 amd64 [installed]
- gnome-shell/bionic-updates,bionic-security,now 3.28.3+git20190124-0ubuntu18.04.2 amd64 [installed]

Reference issue: #68.

**Expected Behaviour**

Login screen is not broken.

**Current Behaviour**

![flex-remix-login-screen-issue-2](https://user-images.githubusercontent.com/8284757/58427964-56884b80-80cb-11e9-88a3-8ec00589253d.jpg)

**Comment by daniruiz** [comment]
flat-remix-gnome-20190526-4 fixes it :wink: 
Thanks for the feedback!
