### ISSUE TITLE
AUR package - Maybe it's not updated?

### ISSUE THREAD

**Issue by fdinardo** [daniruiz/flat-remix-gnome#87]
Hi @daniruiz, thanks for this amazing theme

I am wondering if the aur package is up to date.
Here is an image to explain what I am saying:

![Schermata da 2019-05-30 18-08-32](https://user-images.githubusercontent.com/7387557/58646637-1eb91800-8306-11e9-91b6-75709380a713.png)

You can see that the border of the menu is different from your site preview.
All the dropdown looks different, even the notification/calendar one.
Let me know if I am wrong.

thanks

**Comment by daniruiz** [comment]
Theme screenshots are a bit outdated. As soon as I have some free time I'll replace them with newer ones

**Comment by fdinardo** [comment]
OK thanks, for letting me know.
