### ISSUE TITLE
Request: Dynamic transparency for panel

### ISSUE THREAD

**Issue by ahamadanees-pa** [daniruiz/flat-remix-gnome#88]
Transparent panels are fancy when free-floating but very displeasing with maximised windows. A dynamic-panel variant just like there were in default gnome shell theme would be great.

Unfortunately,This feature is reverted later by stating it "had a negative effect on legibility" which the majority of the users disagrees about. If anyone is interested in doing it, checking the commit [447bf55e](https://gitlab.gnome.org/GNOME/gnome-shell/commit/447bf55e45b00426ed908b1b1035f472c2466956) would be useful.

Also for a fully opaque panel, size and spacing of default theme is seems better.

Edit: Someone [requested](https://github.com/NicoHood/arc-theme/issues/173) the same for arc-theme. I have added screenshots from the issue.

![49686287-9db95a80-faf2-11e8-8a44-3b69e3152636](https://user-images.githubusercontent.com/47503781/58751845-186f9b00-84c2-11e9-9214-9bffc5b3ad2b.png)

![49686288-a1e57800-faf2-11e8-9b56-26000431ac80](https://user-images.githubusercontent.com/47503781/58751846-19a0c800-84c2-11e9-8a8d-40d63b29ffac.png)

**Comment by daniruiz** [comment]
As you said this feature was removed for gnome 3.32 so there is no way I can achieve dynamic transparency for panel. Anyhow, there are already many variants and adding another one for each little thing would be a pain. So the theme will stay as it is for now.

**Comment by ahamadanees-pa** [comment]
> theme will stay as it is for now

Fine

> As you said this feature was removed for gnome 3.32 so there is no way I can achieve dynamic transparency for panel

Whatever feature is introduces or discontinued in gnome's default theme has nothing to do with what we can do in other themes.

**Comment by daniruiz** [comment]
> Whatever feature is introduces or discontinued in gnome's default theme has nothing to do with what we can do in other themes.

https://gitlab.gnome.org/GNOME/gnome-shell/commit/9cfb51c106abd1f96012bf39f3d329cf060035cf
The feature wasn't disabled but removed. There is no way to enable it with a theme.

**Comment by ahamadanees-pa** [comment]
Sorry I may be wrong, but how flat remix themes can still be translucent then. I'm not arguing, just to make clear.

**Comment by ahamadanees-pa** [comment]
Sorry I may be wrong, but how flat remix themes can still be translucent then? I'm not arguing, just to make it clear.

**Comment by daniruiz** [comment]
Transparency wasn't removed, but the ability to modify it dynamically

**Comment by ahamadanees-pa** [comment]
Oh okay. I get it. Anyway ,flat remix is my long time favourite and I will continue to use it even without this feature. Thank you for keeping it alive.
