### ISSUE TITLE
A way to customize the background of the login screen

### ISSUE THREAD

**Issue by LeptoSpira** [daniruiz/flat-remix-gnome#90]
I tried going into the assets folder and changing the `login-background` but no change. It would be nice if the lock screen background was used as the login screen background with an added blur effect.

**Comment by daniruiz** [comment]
I don't understand what you mean. You can actually change the login background of the theme as explained in the README.md. This will use your lock background with the blur effect

`sudo apt install libglib2.0-dev-bin imagemagick` 
```bash
git clone https://github.com/daniruiz/flat-remix-gnome
cd flat-remix-gnome
make && sudo make install
```
![ezgif-1-651b6c814737](https://user-images.githubusercontent.com/12565871/58819083-bc2a8980-862f-11e9-8a8f-f367dbfedcde.gif)


Inside src folder is the build.sh script that has some extra settins, like using a different background image or changing the blur amount.
![image](https://user-images.githubusercontent.com/12565871/58819030-9ac99d80-862f-11e9-981a-2f92a31f112b.png)


After building your custom theme just go back to the main directory and run `sudo make install`

**Comment by LeptoSpira** [comment]
I see now, it was on the same level as "Fedora distributions" So I thought it was just one of the ways to download, not something seperate. How do I install `libglib2.0-dev-bin` and `imagemagick` on Fedora, switching `apt` to `dnf` does not work.

**Comment by LeptoSpira** [comment]
```
# Hundreds of permission denied errors
cp: cannot create regular file '/tmp/flat-remix-gnome/Flat-Remix/pad-osd.css': Permission denied
./build.sh: line 97: glib-compile-resources: command not found
cp: cannot stat '/tmp/flat-remix-gnome/Flat-Remix/gnome-shell-theme.gresource': No such file or directory
make: *** [Makefile:17: all] Error 1
```
This is not resolved by adding `sudo` to the beginning either.

**Comment by LeptoSpira** [comment]
Is this issue still going to be closed?
