### ISSUE TITLE
Shadow turned white

### ISSUE THREAD

**Issue by ahamadanees-pa** [daniruiz/flat-remix-gnome#91]
Flat-Remix_3.32.4
![4p](https://user-images.githubusercontent.com/47503781/58993270-acb36800-880a-11e9-855e-c5af181ed2d2.png)

Newer versions of the same variant 
![post4p](https://user-images.githubusercontent.com/47503781/58993276-ae7d2b80-880a-11e9-9503-6e1fce874818.png)

**Comment by daniruiz** [comment]
Sorry, I have to update all screenshots. Since gnome 3.30 pop-up menus' shadows look choppy, so I replaced them with that glow like border.

**Comment by Kazetoyuki** [comment]
> Sorry, I have to update all screenshots. Since gnome 3.30 pop-up menus' shadows look choppy, so I replaced them with that glow like border.

But this glow border looks not so good, and let pop-up menus large.
With iBus input panel especially. 😖😖😖

**Comment by ahamadanees-pa** [comment]
> > Sorry, I have to update all screenshots. Since gnome 3.30 pop-up menus' shadows look choppy, so I replaced them with that glow like border.
> 
> But this glow border looks not so good, and let pop-up menus large.
> With iBus input panel especially. 
> 
> ![Without Border](https://user-images.githubusercontent.com/3736910/60921927-3785f780-a2ce-11e9-8f16-c1166368d2ac.png)
> ![With Border](https://user-images.githubusercontent.com/3736910/60921929-381e8e00-a2ce-11e9-9619-73cdd61e465d.png)

Yes. very disappointing :pensive:
