### ISSUE TITLE
20190608 version broke the login screen

### ISSUE THREAD

**Issue by tuhz** [daniruiz/flat-remix-gnome#93]
OS: Ubuntu 18.04 LTS in VMware Workstation 15.1.0

The **20190608** update of the flat-remix-gnome package broke the login screen. The list of user names disappeared and I cannot log in. I have tried uninstalling and re-installing the package via apt, but the problem persists.

Screenshot: 
![image](https://user-images.githubusercontent.com/12445237/59224986-44abab80-8b95-11e9-8e64-8747e7259eba.png)

**Comment by tuhz** [comment]
Update: I solved this problem by disabling Wayland. After booting into recovery and uncommenting `WaylandEnable=false` in `/etc/gdm3/custom.conf`, the login screen is now back to normal again.

**Comment by daniruiz** [comment]
Great! :tada: :tada: 
I'll consider it fixed then ;)
