### ISSUE TITLE
Change gnome panel transparency

### ISSUE THREAD

**Issue by MuathAmer** [daniruiz/flat-remix-gnome#94]
I want to change the transparency of Gnome's panel, as it is very transparent.
How can i achieve this? What should I edit?

**Comment by ahamadanees-pa** [comment]
Go to line number 680 of gnome-shell/gnome-shell.css
`background: rgba(0, 0, 0, 0.2);`
Change the value `0.2` to as you wish.

**Comment by MuathAmer** [comment]
How to do this now? I can't find the same line anywhere else.
