### ISSUE TITLE
Blur Effect

### ISSUE THREAD

**Issue by MuathAmer** [daniruiz/flat-remix-gnome#95]
I want to request a blur effect for the shell panel, something that looks like the attached image. 

![Screenshot from 2019-06-17 12-38-13](https://user-images.githubusercontent.com/7873900/59595740-1121d180-90ff-11e9-8735-71cf8a189bd5.png)

**Comment by daniruiz** [comment]
I'd love to add that beautiful blur effect but gnome doesn't support it, even though everyone is asking for it :cry:
