### ISSUE TITLE
Cannot find theme

### ISSUE THREAD

**Issue by ChiDal** [daniruiz/flat-remix-gnome#96]
![Screenshot from 2019-06-20 12-58-46](https://user-images.githubusercontent.com/36493671/59829484-314dcc80-935b-11e9-9166-43978877de6b.png)
Hi, I'm using manjaro 18.0.4. I originally used the manual installation method, then later decided to use the AUR package for automatic updates. When I tried to install the AUR package, there were conflicting files(https://del.dog/lebulugufo), which I deleted manually. Then the installation was successful, but now I can't find the theme in gnome tweaks under 'applications'.
Now, even the manual method (cloning into .themes) doesn't work (I can't see the Flat-Remix option)

I know I'm doing something wrong, just don't know what
![Screenshot from 2019-06-20 12-57-51](https://user-images.githubusercontent.com/36493671/59829427-09f6ff80-935b-11e9-984d-5766ebb020fd.png)
I also tried reinstalling gnome-shell

**Comment by ChiDal** [comment]
Closed because I'm dumb, it was the gtk theme

**Comment by daniruiz** [comment]
That's what I was just about to comment you hehe
It's a common mistake. Don't you worry :smile:

**Comment by ChiDal** [comment]
😂
