### ISSUE TITLE
Ubuntu 19.04 fading to white

### ISSUE THREAD

**Issue by prjoni99** [daniruiz/flat-remix-gnome#99]
Hello I’m having an issue when using the gnome shell theme the desktop fades to white before the display going to sleep and the display almost wakes up immediately for some reason. Was wondering if this something you have seen?

**Comment by aitorCerecetoGlovoApp** [comment]
Same here. White flash and the background is not even changing

**Comment by daniruiz** [comment]
I've change the fading background to black. About the weird behavior waking up immediately, I don't think that's the theme's fault, that makes no sense. But it is also happening to me, I think it only happens when notifications are displayed.

**Comment by prjoni99** [comment]
I figured out the display waking up. If you have an HDMI monitor with
multiple monitors I had to turn off the auto switch input setting on my
monitors. Hope that helps

**Comment by daniruiz** [comment]
@prjoni99 makes sense, I also have multiple monitors and one running over HDMI
So can this issue be closed then?

**Comment by prjoni99** [comment]
Yes! Thank you so much
